package com.google.appinventor.components.runtime;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Looper;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;
import com.google.appinventor.common.version.AppInventorFeatures;
import com.google.appinventor.components.annotations.SimpleObject;
import com.google.appinventor.components.annotations.SimpleProperty;
import com.google.appinventor.components.runtime.util.AppInvHTTPD;
import com.google.appinventor.components.runtime.util.OnInitializeListener;
import com.google.appinventor.components.runtime.util.QUtil;
import com.google.appinventor.components.runtime.util.RetValManager;
import com.google.appinventor.components.runtime.util.WebRTCNativeMgr;
import dalvik.system.DexClassLoader;
import gnu.expr.Language;
import gnu.expr.ModuleExp;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import kawa.standard.Scheme;

public class ReplForm extends Form {
  private static final String LOG_TAG = ReplForm.class.getSimpleName();
  
  private static final String SPLASH_ACTIVITY_CLASS = SplashActivity.class.getName();
  
  public static ReplForm topform;
  
  private boolean IsUSBRepl = false;
  
  private boolean assetsLoaded = false;
  
  private String currentTheme = "Classic";
  
  private AppInvHTTPD httpdServer = null;
  
  private boolean isDirect = false;
  
  private List<String> loadedExternalDexs;
  
  private String replAssetDir;
  
  private String replCompDir;
  
  private Object replResult = null;
  
  private String replResultFormName = null;
  
  SchemeInterface schemeInterface = new SchemeInterface();
  
  private WebRTCNativeMgr webRTCNativeMgr;
  
  public ReplForm() {
    topform = this;
  }
  
  private void checkAssetDir() {
    File file = new File(this.replAssetDir);
    if (!file.exists())
      file.mkdirs(); 
  }
  
  private boolean checkComponentDir() {
    File file = new File(this.replCompDir);
    return !file.exists() ? file.mkdirs() : true;
  }
  
  private String genReportId() {
    String[] arrayOfString = new String[2048];
    arrayOfString[0] = "A";
    arrayOfString[1] = "ABE";
    arrayOfString[2] = "ACE";
    arrayOfString[3] = "ACT";
    arrayOfString[4] = "AD";
    arrayOfString[5] = "ADA";
    arrayOfString[6] = "ADD";
    arrayOfString[7] = "AGO";
    arrayOfString[8] = "AID";
    arrayOfString[9] = "AIM";
    arrayOfString[10] = "AIR";
    arrayOfString[11] = "ALL";
    arrayOfString[12] = "ALP";
    arrayOfString[13] = "AM";
    arrayOfString[14] = "AMY";
    arrayOfString[15] = "AN";
    arrayOfString[16] = "ANA";
    arrayOfString[17] = "AND";
    arrayOfString[18] = "ANN";
    arrayOfString[19] = "ANT";
    arrayOfString[20] = "ANY";
    arrayOfString[21] = "APE";
    arrayOfString[22] = "APS";
    arrayOfString[23] = "APT";
    arrayOfString[24] = "ARC";
    arrayOfString[25] = "ARE";
    arrayOfString[26] = "ARK";
    arrayOfString[27] = "ARM";
    arrayOfString[28] = "ART";
    arrayOfString[29] = "AS";
    arrayOfString[30] = "ASH";
    arrayOfString[31] = "ASK";
    arrayOfString[32] = "AT";
    arrayOfString[33] = "ATE";
    arrayOfString[34] = "AUG";
    arrayOfString[35] = "AUK";
    arrayOfString[36] = "AVE";
    arrayOfString[37] = "AWE";
    arrayOfString[38] = "AWK";
    arrayOfString[39] = "AWL";
    arrayOfString[40] = "AWN";
    arrayOfString[41] = "AX";
    arrayOfString[42] = "AYE";
    arrayOfString[43] = "BAD";
    arrayOfString[44] = "BAG";
    arrayOfString[45] = "BAH";
    arrayOfString[46] = "BAM";
    arrayOfString[47] = "BAN";
    arrayOfString[48] = "BAR";
    arrayOfString[49] = "BAT";
    arrayOfString[50] = "BAY";
    arrayOfString[51] = "BE";
    arrayOfString[52] = "BED";
    arrayOfString[53] = "BEE";
    arrayOfString[54] = "BEG";
    arrayOfString[55] = "BEN";
    arrayOfString[56] = "BET";
    arrayOfString[57] = "BEY";
    arrayOfString[58] = "BIB";
    arrayOfString[59] = "BID";
    arrayOfString[60] = "BIG";
    arrayOfString[61] = "BIN";
    arrayOfString[62] = "BIT";
    arrayOfString[63] = "BOB";
    arrayOfString[64] = "BOG";
    arrayOfString[65] = "BON";
    arrayOfString[66] = "BOO";
    arrayOfString[67] = "BOP";
    arrayOfString[68] = "BOW";
    arrayOfString[69] = "BOY";
    arrayOfString[70] = "BUB";
    arrayOfString[71] = "BUD";
    arrayOfString[72] = "BUG";
    arrayOfString[73] = "BUM";
    arrayOfString[74] = "BUN";
    arrayOfString[75] = "BUS";
    arrayOfString[76] = "BUT";
    arrayOfString[77] = "BUY";
    arrayOfString[78] = "BY";
    arrayOfString[79] = "BYE";
    arrayOfString[80] = "CAB";
    arrayOfString[81] = "CAL";
    arrayOfString[82] = "CAM";
    arrayOfString[83] = "CAN";
    arrayOfString[84] = "CAP";
    arrayOfString[85] = "CAR";
    arrayOfString[86] = "CAT";
    arrayOfString[87] = "CAW";
    arrayOfString[88] = "COD";
    arrayOfString[89] = "COG";
    arrayOfString[90] = "COL";
    arrayOfString[91] = "CON";
    arrayOfString[92] = "COO";
    arrayOfString[93] = "COP";
    arrayOfString[94] = "COT";
    arrayOfString[95] = "COW";
    arrayOfString[96] = "COY";
    arrayOfString[97] = "CRY";
    arrayOfString[98] = "CUB";
    arrayOfString[99] = "CUE";
    arrayOfString[100] = "CUP";
    arrayOfString[101] = "CUR";
    arrayOfString[102] = "CUT";
    arrayOfString[103] = "DAB";
    arrayOfString[104] = "DAD";
    arrayOfString[105] = "DAM";
    arrayOfString[106] = "DAN";
    arrayOfString[107] = "DAR";
    arrayOfString[108] = "DAY";
    arrayOfString[109] = "DEE";
    arrayOfString[110] = "DEL";
    arrayOfString[111] = "DEN";
    arrayOfString[112] = "DES";
    arrayOfString[113] = "DEW";
    arrayOfString[114] = "DID";
    arrayOfString[115] = "DIE";
    arrayOfString[116] = "DIG";
    arrayOfString[117] = "DIN";
    arrayOfString[118] = "DIP";
    arrayOfString[119] = "DO";
    arrayOfString[120] = "DOE";
    arrayOfString[121] = "DOG";
    arrayOfString[122] = "DON";
    arrayOfString[123] = "DOT";
    arrayOfString[124] = "DOW";
    arrayOfString[125] = "DRY";
    arrayOfString[126] = "DUB";
    arrayOfString[127] = "DUD";
    arrayOfString[128] = "DUE";
    arrayOfString[129] = "DUG";
    arrayOfString[130] = "DUN";
    arrayOfString[131] = "EAR";
    arrayOfString[132] = "EAT";
    arrayOfString[133] = "ED";
    arrayOfString[134] = "EEL";
    arrayOfString[135] = "EGG";
    arrayOfString[136] = "EGO";
    arrayOfString[137] = "ELI";
    arrayOfString[138] = "ELK";
    arrayOfString[139] = "ELM";
    arrayOfString[140] = "ELY";
    arrayOfString[141] = "EM";
    arrayOfString[142] = "END";
    arrayOfString[143] = "EST";
    arrayOfString[144] = "ETC";
    arrayOfString[145] = "EVA";
    arrayOfString[146] = "EVE";
    arrayOfString[147] = "EWE";
    arrayOfString[148] = "EYE";
    arrayOfString[149] = "FAD";
    arrayOfString[150] = "FAN";
    arrayOfString[151] = "FAR";
    arrayOfString[152] = "FAT";
    arrayOfString[153] = "FAY";
    arrayOfString[154] = "FED";
    arrayOfString[155] = "FEE";
    arrayOfString[156] = "FEW";
    arrayOfString[157] = "FIB";
    arrayOfString[158] = "FIG";
    arrayOfString[159] = "FIN";
    arrayOfString[160] = "FIR";
    arrayOfString[161] = "FIT";
    arrayOfString[162] = "FLO";
    arrayOfString[163] = "FLY";
    arrayOfString[164] = "FOE";
    arrayOfString[165] = "FOG";
    arrayOfString[166] = "FOR";
    arrayOfString[167] = "FRY";
    arrayOfString[168] = "FUM";
    arrayOfString[169] = "FUN";
    arrayOfString[170] = "FUR";
    arrayOfString[171] = "GAB";
    arrayOfString[172] = "GAD";
    arrayOfString[173] = "GAG";
    arrayOfString[174] = "GAL";
    arrayOfString[175] = "GAM";
    arrayOfString[176] = "GAP";
    arrayOfString[177] = "GAS";
    arrayOfString[178] = "GAY";
    arrayOfString[179] = "GEE";
    arrayOfString[180] = "GEL";
    arrayOfString[181] = "GEM";
    arrayOfString[182] = "GET";
    arrayOfString[183] = "GIG";
    arrayOfString[184] = "GIL";
    arrayOfString[185] = "GIN";
    arrayOfString[186] = "GO";
    arrayOfString[187] = "GOT";
    arrayOfString[188] = "GUM";
    arrayOfString[189] = "GUN";
    arrayOfString[190] = "GUS";
    arrayOfString[191] = "GUT";
    arrayOfString[192] = "GUY";
    arrayOfString[193] = "GYM";
    arrayOfString[194] = "GYP";
    arrayOfString[195] = "HA";
    arrayOfString[196] = "HAD";
    arrayOfString[197] = "HAL";
    arrayOfString[198] = "HAM";
    arrayOfString[199] = "HAN";
    arrayOfString[200] = "HAP";
    arrayOfString[201] = "HAS";
    arrayOfString[202] = "HAT";
    arrayOfString[203] = "HAW";
    arrayOfString[204] = "HAY";
    arrayOfString[205] = "HE";
    arrayOfString[206] = "HEM";
    arrayOfString[207] = "HEN";
    arrayOfString[208] = "HER";
    arrayOfString[209] = "HEW";
    arrayOfString[210] = "HEY";
    arrayOfString[211] = "HI";
    arrayOfString[212] = "HID";
    arrayOfString[213] = "HIM";
    arrayOfString[214] = "HIP";
    arrayOfString[215] = "HIS";
    arrayOfString[216] = "HIT";
    arrayOfString[217] = "HO";
    arrayOfString[218] = "HOB";
    arrayOfString[219] = "HOC";
    arrayOfString[220] = "HOE";
    arrayOfString[221] = "HOG";
    arrayOfString[222] = "HOP";
    arrayOfString[223] = "HOT";
    arrayOfString[224] = "HOW";
    arrayOfString[225] = "HUB";
    arrayOfString[226] = "HUE";
    arrayOfString[227] = "HUG";
    arrayOfString[228] = "HUH";
    arrayOfString[229] = "HUM";
    arrayOfString[230] = "HUT";
    arrayOfString[231] = "I";
    arrayOfString[232] = "ICY";
    arrayOfString[233] = "IDA";
    arrayOfString[234] = "IF";
    arrayOfString[235] = "IKE";
    arrayOfString[236] = "ILL";
    arrayOfString[237] = "INK";
    arrayOfString[238] = "INN";
    arrayOfString[239] = "IO";
    arrayOfString[240] = "ION";
    arrayOfString[241] = "IQ";
    arrayOfString[242] = "IRA";
    arrayOfString[243] = "IRE";
    arrayOfString[244] = "IRK";
    arrayOfString[245] = "IS";
    arrayOfString[246] = "IT";
    arrayOfString[247] = "ITS";
    arrayOfString[248] = "IVY";
    arrayOfString[249] = "JAB";
    arrayOfString[250] = "JAG";
    arrayOfString[251] = "JAM";
    arrayOfString[252] = "JAN";
    arrayOfString[253] = "JAR";
    arrayOfString[254] = "JAW";
    arrayOfString[255] = "JAY";
    arrayOfString[256] = "JET";
    arrayOfString[257] = "JIG";
    arrayOfString[258] = "JIM";
    arrayOfString[259] = "JO";
    arrayOfString[260] = "JOB";
    arrayOfString[261] = "JOE";
    arrayOfString[262] = "JOG";
    arrayOfString[263] = "JOT";
    arrayOfString[264] = "JOY";
    arrayOfString[265] = "JUG";
    arrayOfString[266] = "JUT";
    arrayOfString[267] = "KAY";
    arrayOfString[268] = "KEG";
    arrayOfString[269] = "KEN";
    arrayOfString[270] = "KEY";
    arrayOfString[271] = "KID";
    arrayOfString[272] = "KIM";
    arrayOfString[273] = "KIN";
    arrayOfString[274] = "KIT";
    arrayOfString[275] = "LA";
    arrayOfString[276] = "LAB";
    arrayOfString[277] = "LAC";
    arrayOfString[278] = "LAD";
    arrayOfString[279] = "LAG";
    arrayOfString[280] = "LAM";
    arrayOfString[281] = "LAP";
    arrayOfString[282] = "LAW";
    arrayOfString[283] = "LAY";
    arrayOfString[284] = "LEA";
    arrayOfString[285] = "LED";
    arrayOfString[286] = "LEE";
    arrayOfString[287] = "LEG";
    arrayOfString[288] = "LEN";
    arrayOfString[289] = "LEO";
    arrayOfString[290] = "LET";
    arrayOfString[291] = "LEW";
    arrayOfString[292] = "LID";
    arrayOfString[293] = "LIE";
    arrayOfString[294] = "LIN";
    arrayOfString[295] = "LIP";
    arrayOfString[296] = "LIT";
    arrayOfString[297] = "LO";
    arrayOfString[298] = "LOB";
    arrayOfString[299] = "LOG";
    arrayOfString[300] = "LOP";
    arrayOfString[301] = "LOS";
    arrayOfString[302] = "LOT";
    arrayOfString[303] = "LOU";
    arrayOfString[304] = "LOW";
    arrayOfString[305] = "LOY";
    arrayOfString[306] = "LUG";
    arrayOfString[307] = "LYE";
    arrayOfString[308] = "MA";
    arrayOfString[309] = "MAC";
    arrayOfString[310] = "MAD";
    arrayOfString[311] = "MAE";
    arrayOfString[312] = "MAN";
    arrayOfString[313] = "MAO";
    arrayOfString[314] = "MAP";
    arrayOfString[315] = "MAT";
    arrayOfString[316] = "MAW";
    arrayOfString[317] = "MAY";
    arrayOfString[318] = "ME";
    arrayOfString[319] = "MEG";
    arrayOfString[320] = "MEL";
    arrayOfString[321] = "MEN";
    arrayOfString[322] = "MET";
    arrayOfString[323] = "MEW";
    arrayOfString[324] = "MID";
    arrayOfString[325] = "MIN";
    arrayOfString[326] = "MIT";
    arrayOfString[327] = "MOB";
    arrayOfString[328] = "MOD";
    arrayOfString[329] = "MOE";
    arrayOfString[330] = "MOO";
    arrayOfString[331] = "MOP";
    arrayOfString[332] = "MOS";
    arrayOfString[333] = "MOT";
    arrayOfString[334] = "MOW";
    arrayOfString[335] = "MUD";
    arrayOfString[336] = "MUG";
    arrayOfString[337] = "MUM";
    arrayOfString[338] = "MY";
    arrayOfString[339] = "NAB";
    arrayOfString[340] = "NAG";
    arrayOfString[341] = "NAN";
    arrayOfString[342] = "NAP";
    arrayOfString[343] = "NAT";
    arrayOfString[344] = "NAY";
    arrayOfString[345] = "NE";
    arrayOfString[346] = "NED";
    arrayOfString[347] = "NEE";
    arrayOfString[348] = "NET";
    arrayOfString[349] = "NEW";
    arrayOfString[350] = "NIB";
    arrayOfString[351] = "NIL";
    arrayOfString[352] = "NIP";
    arrayOfString[353] = "NIT";
    arrayOfString[354] = "NO";
    arrayOfString[355] = "NOB";
    arrayOfString[356] = "NOD";
    arrayOfString[357] = "NON";
    arrayOfString[358] = "NOR";
    arrayOfString[359] = "NOT";
    arrayOfString[360] = "NOV";
    arrayOfString[361] = "NOW";
    arrayOfString[362] = "NU";
    arrayOfString[363] = "NUN";
    arrayOfString[364] = "NUT";
    arrayOfString[365] = "O";
    arrayOfString[366] = "OAF";
    arrayOfString[367] = "OAK";
    arrayOfString[368] = "OAR";
    arrayOfString[369] = "OAT";
    arrayOfString[370] = "ODD";
    arrayOfString[371] = "ODE";
    arrayOfString[372] = "OF";
    arrayOfString[373] = "OFF";
    arrayOfString[374] = "OFT";
    arrayOfString[375] = "OH";
    arrayOfString[376] = "OIL";
    arrayOfString[377] = "OK";
    arrayOfString[378] = "OLD";
    arrayOfString[379] = "ON";
    arrayOfString[380] = "ONE";
    arrayOfString[381] = "OR";
    arrayOfString[382] = "ORB";
    arrayOfString[383] = "ORE";
    arrayOfString[384] = "ORR";
    arrayOfString[385] = "OS";
    arrayOfString[386] = "OTT";
    arrayOfString[387] = "OUR";
    arrayOfString[388] = "OUT";
    arrayOfString[389] = "OVA";
    arrayOfString[390] = "OW";
    arrayOfString[391] = "OWE";
    arrayOfString[392] = "OWL";
    arrayOfString[393] = "OWN";
    arrayOfString[394] = "OX";
    arrayOfString[395] = "PA";
    arrayOfString[396] = "PAD";
    arrayOfString[397] = "PAL";
    arrayOfString[398] = "PAM";
    arrayOfString[399] = "PAN";
    arrayOfString[400] = "PAP";
    arrayOfString[401] = "PAR";
    arrayOfString[402] = "PAT";
    arrayOfString[403] = "PAW";
    arrayOfString[404] = "PAY";
    arrayOfString[405] = "PEA";
    arrayOfString[406] = "PEG";
    arrayOfString[407] = "PEN";
    arrayOfString[408] = "PEP";
    arrayOfString[409] = "PER";
    arrayOfString[410] = "PET";
    arrayOfString[411] = "PEW";
    arrayOfString[412] = "PHI";
    arrayOfString[413] = "PI";
    arrayOfString[414] = "PIE";
    arrayOfString[415] = "PIN";
    arrayOfString[416] = "PIT";
    arrayOfString[417] = "PLY";
    arrayOfString[418] = "PO";
    arrayOfString[419] = "POD";
    arrayOfString[420] = "POE";
    arrayOfString[421] = "POP";
    arrayOfString[422] = "POT";
    arrayOfString[423] = "POW";
    arrayOfString[424] = "PRO";
    arrayOfString[425] = "PRY";
    arrayOfString[426] = "PUB";
    arrayOfString[427] = "PUG";
    arrayOfString[428] = "PUN";
    arrayOfString[429] = "PUP";
    arrayOfString[430] = "PUT";
    arrayOfString[431] = "QUO";
    arrayOfString[432] = "RAG";
    arrayOfString[433] = "RAM";
    arrayOfString[434] = "RAN";
    arrayOfString[435] = "RAP";
    arrayOfString[436] = "RAT";
    arrayOfString[437] = "RAW";
    arrayOfString[438] = "RAY";
    arrayOfString[439] = "REB";
    arrayOfString[440] = "RED";
    arrayOfString[441] = "REP";
    arrayOfString[442] = "RET";
    arrayOfString[443] = "RIB";
    arrayOfString[444] = "RID";
    arrayOfString[445] = "RIG";
    arrayOfString[446] = "RIM";
    arrayOfString[447] = "RIO";
    arrayOfString[448] = "RIP";
    arrayOfString[449] = "ROB";
    arrayOfString[450] = "ROD";
    arrayOfString[451] = "ROE";
    arrayOfString[452] = "RON";
    arrayOfString[453] = "ROT";
    arrayOfString[454] = "ROW";
    arrayOfString[455] = "ROY";
    arrayOfString[456] = "RUB";
    arrayOfString[457] = "RUE";
    arrayOfString[458] = "RUG";
    arrayOfString[459] = "RUM";
    arrayOfString[460] = "RUN";
    arrayOfString[461] = "RYE";
    arrayOfString[462] = "SAC";
    arrayOfString[463] = "SAD";
    arrayOfString[464] = "SAG";
    arrayOfString[465] = "SAL";
    arrayOfString[466] = "SAM";
    arrayOfString[467] = "SAN";
    arrayOfString[468] = "SAP";
    arrayOfString[469] = "SAT";
    arrayOfString[470] = "SAW";
    arrayOfString[471] = "SAY";
    arrayOfString[472] = "SEA";
    arrayOfString[473] = "SEC";
    arrayOfString[474] = "SEE";
    arrayOfString[475] = "SEN";
    arrayOfString[476] = "SET";
    arrayOfString[477] = "SEW";
    arrayOfString[478] = "SHE";
    arrayOfString[479] = "SHY";
    arrayOfString[480] = "SIN";
    arrayOfString[481] = "SIP";
    arrayOfString[482] = "SIR";
    arrayOfString[483] = "SIS";
    arrayOfString[484] = "SIT";
    arrayOfString[485] = "SKI";
    arrayOfString[486] = "SKY";
    arrayOfString[487] = "SLY";
    arrayOfString[488] = "SO";
    arrayOfString[489] = "SOB";
    arrayOfString[490] = "SOD";
    arrayOfString[491] = "SON";
    arrayOfString[492] = "SOP";
    arrayOfString[493] = "SOW";
    arrayOfString[494] = "SOY";
    arrayOfString[495] = "SPA";
    arrayOfString[496] = "SPY";
    arrayOfString[497] = "SUB";
    arrayOfString[498] = "SUD";
    arrayOfString[499] = "SUE";
    arrayOfString[500] = "SUM";
    arrayOfString[501] = "SUN";
    arrayOfString[502] = "SUP";
    arrayOfString[503] = "TAB";
    arrayOfString[504] = "TAD";
    arrayOfString[505] = "TAG";
    arrayOfString[506] = "TAN";
    arrayOfString[507] = "TAP";
    arrayOfString[508] = "TAR";
    arrayOfString[509] = "TEA";
    arrayOfString[510] = "TED";
    arrayOfString[511] = "TEE";
    arrayOfString[512] = "TEN";
    arrayOfString[513] = "THE";
    arrayOfString[514] = "THY";
    arrayOfString[515] = "TIC";
    arrayOfString[516] = "TIE";
    arrayOfString[517] = "TIM";
    arrayOfString[518] = "TIN";
    arrayOfString[519] = "TIP";
    arrayOfString[520] = "TO";
    arrayOfString[521] = "TOE";
    arrayOfString[522] = "TOG";
    arrayOfString[523] = "TOM";
    arrayOfString[524] = "TON";
    arrayOfString[525] = "TOO";
    arrayOfString[526] = "TOP";
    arrayOfString[527] = "TOW";
    arrayOfString[528] = "TOY";
    arrayOfString[529] = "TRY";
    arrayOfString[530] = "TUB";
    arrayOfString[531] = "TUG";
    arrayOfString[532] = "TUM";
    arrayOfString[533] = "TUN";
    arrayOfString[534] = "TWO";
    arrayOfString[535] = "UN";
    arrayOfString[536] = "UP";
    arrayOfString[537] = "US";
    arrayOfString[538] = "USE";
    arrayOfString[539] = "VAN";
    arrayOfString[540] = "VAT";
    arrayOfString[541] = "VET";
    arrayOfString[542] = "VIE";
    arrayOfString[543] = "WAD";
    arrayOfString[544] = "WAG";
    arrayOfString[545] = "WAR";
    arrayOfString[546] = "WAS";
    arrayOfString[547] = "WAY";
    arrayOfString[548] = "WE";
    arrayOfString[549] = "WEB";
    arrayOfString[550] = "WED";
    arrayOfString[551] = "WEE";
    arrayOfString[552] = "WET";
    arrayOfString[553] = "WHO";
    arrayOfString[554] = "WHY";
    arrayOfString[555] = "WIN";
    arrayOfString[556] = "WIT";
    arrayOfString[557] = "WOK";
    arrayOfString[558] = "WON";
    arrayOfString[559] = "WOO";
    arrayOfString[560] = "WOW";
    arrayOfString[561] = "WRY";
    arrayOfString[562] = "WU";
    arrayOfString[563] = "YAM";
    arrayOfString[564] = "YAP";
    arrayOfString[565] = "YAW";
    arrayOfString[566] = "YE";
    arrayOfString[567] = "YEA";
    arrayOfString[568] = "YES";
    arrayOfString[569] = "YET";
    arrayOfString[570] = "YOU";
    arrayOfString[571] = "ABED";
    arrayOfString[572] = "ABEL";
    arrayOfString[573] = "ABET";
    arrayOfString[574] = "ABLE";
    arrayOfString[575] = "ABUT";
    arrayOfString[576] = "ACHE";
    arrayOfString[577] = "ACID";
    arrayOfString[578] = "ACME";
    arrayOfString[579] = "ACRE";
    arrayOfString[580] = "ACTA";
    arrayOfString[581] = "ACTS";
    arrayOfString[582] = "ADAM";
    arrayOfString[583] = "ADDS";
    arrayOfString[584] = "ADEN";
    arrayOfString[585] = "AFAR";
    arrayOfString[586] = "AFRO";
    arrayOfString[587] = "AGEE";
    arrayOfString[588] = "AHEM";
    arrayOfString[589] = "AHOY";
    arrayOfString[590] = "AIDA";
    arrayOfString[591] = "AIDE";
    arrayOfString[592] = "AIDS";
    arrayOfString[593] = "AIRY";
    arrayOfString[594] = "AJAR";
    arrayOfString[595] = "AKIN";
    arrayOfString[596] = "ALAN";
    arrayOfString[597] = "ALEC";
    arrayOfString[598] = "ALGA";
    arrayOfString[599] = "ALIA";
    arrayOfString[600] = "ALLY";
    arrayOfString[601] = "ALMA";
    arrayOfString[602] = "ALOE";
    arrayOfString[603] = "ALSO";
    arrayOfString[604] = "ALTO";
    arrayOfString[605] = "ALUM";
    arrayOfString[606] = "ALVA";
    arrayOfString[607] = "AMEN";
    arrayOfString[608] = "AMES";
    arrayOfString[609] = "AMID";
    arrayOfString[610] = "AMMO";
    arrayOfString[611] = "AMOK";
    arrayOfString[612] = "AMOS";
    arrayOfString[613] = "AMRA";
    arrayOfString[614] = "ANDY";
    arrayOfString[615] = "ANEW";
    arrayOfString[616] = "ANNA";
    arrayOfString[617] = "ANNE";
    arrayOfString[618] = "ANTE";
    arrayOfString[619] = "ANTI";
    arrayOfString[620] = "AQUA";
    arrayOfString[621] = "ARAB";
    arrayOfString[622] = "ARCH";
    arrayOfString[623] = "AREA";
    arrayOfString[624] = "ARGO";
    arrayOfString[625] = "ARID";
    arrayOfString[626] = "ARMY";
    arrayOfString[627] = "ARTS";
    arrayOfString[628] = "ARTY";
    arrayOfString[629] = "ASIA";
    arrayOfString[630] = "ASKS";
    arrayOfString[631] = "ATOM";
    arrayOfString[632] = "AUNT";
    arrayOfString[633] = "AURA";
    arrayOfString[634] = "AUTO";
    arrayOfString[635] = "AVER";
    arrayOfString[636] = "AVID";
    arrayOfString[637] = "AVIS";
    arrayOfString[638] = "AVON";
    arrayOfString[639] = "AVOW";
    arrayOfString[640] = "AWAY";
    arrayOfString[641] = "AWRY";
    arrayOfString[642] = "BABE";
    arrayOfString[643] = "BABY";
    arrayOfString[644] = "BACH";
    arrayOfString[645] = "BACK";
    arrayOfString[646] = "BADE";
    arrayOfString[647] = "BAIL";
    arrayOfString[648] = "BAIT";
    arrayOfString[649] = "BAKE";
    arrayOfString[650] = "BALD";
    arrayOfString[651] = "BALE";
    arrayOfString[652] = "BALI";
    arrayOfString[653] = "BALK";
    arrayOfString[654] = "BALL";
    arrayOfString[655] = "BALM";
    arrayOfString[656] = "BAND";
    arrayOfString[657] = "BANE";
    arrayOfString[658] = "BANG";
    arrayOfString[659] = "BANK";
    arrayOfString[660] = "BARB";
    arrayOfString[661] = "BARD";
    arrayOfString[662] = "BARE";
    arrayOfString[663] = "BARK";
    arrayOfString[664] = "BARN";
    arrayOfString[665] = "BARR";
    arrayOfString[666] = "BASE";
    arrayOfString[667] = "BASH";
    arrayOfString[668] = "BASK";
    arrayOfString[669] = "BASS";
    arrayOfString[670] = "BATE";
    arrayOfString[671] = "BATH";
    arrayOfString[672] = "BAWD";
    arrayOfString[673] = "BAWL";
    arrayOfString[674] = "BEAD";
    arrayOfString[675] = "BEAK";
    arrayOfString[676] = "BEAM";
    arrayOfString[677] = "BEAN";
    arrayOfString[678] = "BEAR";
    arrayOfString[679] = "BEAT";
    arrayOfString[680] = "BEAU";
    arrayOfString[681] = "BECK";
    arrayOfString[682] = "BEEF";
    arrayOfString[683] = "BEEN";
    arrayOfString[684] = "BEER";
    arrayOfString[685] = "BEET";
    arrayOfString[686] = "BELA";
    arrayOfString[687] = "BELL";
    arrayOfString[688] = "BELT";
    arrayOfString[689] = "BEND";
    arrayOfString[690] = "BENT";
    arrayOfString[691] = "BERG";
    arrayOfString[692] = "BERN";
    arrayOfString[693] = "BERT";
    arrayOfString[694] = "BESS";
    arrayOfString[695] = "BEST";
    arrayOfString[696] = "BETA";
    arrayOfString[697] = "BETH";
    arrayOfString[698] = "BHOY";
    arrayOfString[699] = "BIAS";
    arrayOfString[700] = "BIDE";
    arrayOfString[701] = "BIEN";
    arrayOfString[702] = "BILE";
    arrayOfString[703] = "BILK";
    arrayOfString[704] = "BILL";
    arrayOfString[705] = "BIND";
    arrayOfString[706] = "BING";
    arrayOfString[707] = "BIRD";
    arrayOfString[708] = "BITE";
    arrayOfString[709] = "BITS";
    arrayOfString[710] = "BLAB";
    arrayOfString[711] = "BLAT";
    arrayOfString[712] = "BLED";
    arrayOfString[713] = "BLEW";
    arrayOfString[714] = "BLOB";
    arrayOfString[715] = "BLOC";
    arrayOfString[716] = "BLOT";
    arrayOfString[717] = "BLOW";
    arrayOfString[718] = "BLUE";
    arrayOfString[719] = "BLUM";
    arrayOfString[720] = "BLUR";
    arrayOfString[721] = "BOAR";
    arrayOfString[722] = "BOAT";
    arrayOfString[723] = "BOCA";
    arrayOfString[724] = "BOCK";
    arrayOfString[725] = "BODE";
    arrayOfString[726] = "BODY";
    arrayOfString[727] = "BOGY";
    arrayOfString[728] = "BOHR";
    arrayOfString[729] = "BOIL";
    arrayOfString[730] = "BOLD";
    arrayOfString[731] = "BOLO";
    arrayOfString[732] = "BOLT";
    arrayOfString[733] = "BOMB";
    arrayOfString[734] = "BONA";
    arrayOfString[735] = "BOND";
    arrayOfString[736] = "BONE";
    arrayOfString[737] = "BONG";
    arrayOfString[738] = "BONN";
    arrayOfString[739] = "BONY";
    arrayOfString[740] = "BOOK";
    arrayOfString[741] = "BOOM";
    arrayOfString[742] = "BOON";
    arrayOfString[743] = "BOOT";
    arrayOfString[744] = "BORE";
    arrayOfString[745] = "BORG";
    arrayOfString[746] = "BORN";
    arrayOfString[747] = "BOSE";
    arrayOfString[748] = "BOSS";
    arrayOfString[749] = "BOTH";
    arrayOfString[750] = "BOUT";
    arrayOfString[751] = "BOWL";
    arrayOfString[752] = "BOYD";
    arrayOfString[753] = "BRAD";
    arrayOfString[754] = "BRAE";
    arrayOfString[755] = "BRAG";
    arrayOfString[756] = "BRAN";
    arrayOfString[757] = "BRAY";
    arrayOfString[758] = "BRED";
    arrayOfString[759] = "BREW";
    arrayOfString[760] = "BRIG";
    arrayOfString[761] = "BRIM";
    arrayOfString[762] = "BROW";
    arrayOfString[763] = "BUCK";
    arrayOfString[764] = "BUDD";
    arrayOfString[765] = "BUFF";
    arrayOfString[766] = "BULB";
    arrayOfString[767] = "BULK";
    arrayOfString[768] = "BULL";
    arrayOfString[769] = "BUNK";
    arrayOfString[770] = "BUNT";
    arrayOfString[771] = "BUOY";
    arrayOfString[772] = "BURG";
    arrayOfString[773] = "BURL";
    arrayOfString[774] = "BURN";
    arrayOfString[775] = "BURR";
    arrayOfString[776] = "BURT";
    arrayOfString[777] = "BURY";
    arrayOfString[778] = "BUSH";
    arrayOfString[779] = "BUSS";
    arrayOfString[780] = "BUST";
    arrayOfString[781] = "BUSY";
    arrayOfString[782] = "BYTE";
    arrayOfString[783] = "CADY";
    arrayOfString[784] = "CAFE";
    arrayOfString[785] = "CAGE";
    arrayOfString[786] = "CAIN";
    arrayOfString[787] = "CAKE";
    arrayOfString[788] = "CALF";
    arrayOfString[789] = "CALL";
    arrayOfString[790] = "CALM";
    arrayOfString[791] = "CAME";
    arrayOfString[792] = "CANE";
    arrayOfString[793] = "CANT";
    arrayOfString[794] = "CARD";
    arrayOfString[795] = "CARE";
    arrayOfString[796] = "CARL";
    arrayOfString[797] = "CARR";
    arrayOfString[798] = "CART";
    arrayOfString[799] = "CASE";
    arrayOfString[800] = "CASH";
    arrayOfString[801] = "CASK";
    arrayOfString[802] = "CAST";
    arrayOfString[803] = "CAVE";
    arrayOfString[804] = "CEIL";
    arrayOfString[805] = "CELL";
    arrayOfString[806] = "CENT";
    arrayOfString[807] = "CERN";
    arrayOfString[808] = "CHAD";
    arrayOfString[809] = "CHAR";
    arrayOfString[810] = "CHAT";
    arrayOfString[811] = "CHAW";
    arrayOfString[812] = "CHEF";
    arrayOfString[813] = "CHEN";
    arrayOfString[814] = "CHEW";
    arrayOfString[815] = "CHIC";
    arrayOfString[816] = "CHIN";
    arrayOfString[817] = "CHOU";
    arrayOfString[818] = "CHOW";
    arrayOfString[819] = "CHUB";
    arrayOfString[820] = "CHUG";
    arrayOfString[821] = "CHUM";
    arrayOfString[822] = "CITE";
    arrayOfString[823] = "CITY";
    arrayOfString[824] = "CLAD";
    arrayOfString[825] = "CLAM";
    arrayOfString[826] = "CLAN";
    arrayOfString[827] = "CLAW";
    arrayOfString[828] = "CLAY";
    arrayOfString[829] = "CLOD";
    arrayOfString[830] = "CLOG";
    arrayOfString[831] = "CLOT";
    arrayOfString[832] = "CLUB";
    arrayOfString[833] = "CLUE";
    arrayOfString[834] = "COAL";
    arrayOfString[835] = "COAT";
    arrayOfString[836] = "COCA";
    arrayOfString[837] = "COCK";
    arrayOfString[838] = "COCO";
    arrayOfString[839] = "CODA";
    arrayOfString[840] = "CODE";
    arrayOfString[841] = "CODY";
    arrayOfString[842] = "COED";
    arrayOfString[843] = "COIL";
    arrayOfString[844] = "COIN";
    arrayOfString[845] = "COKE";
    arrayOfString[846] = "COLA";
    arrayOfString[847] = "COLD";
    arrayOfString[848] = "COLT";
    arrayOfString[849] = "COMA";
    arrayOfString[850] = "COMB";
    arrayOfString[851] = "COME";
    arrayOfString[852] = "COOK";
    arrayOfString[853] = "COOL";
    arrayOfString[854] = "COON";
    arrayOfString[855] = "COOT";
    arrayOfString[856] = "CORD";
    arrayOfString[857] = "CORE";
    arrayOfString[858] = "CORK";
    arrayOfString[859] = "CORN";
    arrayOfString[860] = "COST";
    arrayOfString[861] = "COVE";
    arrayOfString[862] = "COWL";
    arrayOfString[863] = "CRAB";
    arrayOfString[864] = "CRAG";
    arrayOfString[865] = "CRAM";
    arrayOfString[866] = "CRAY";
    arrayOfString[867] = "CREW";
    arrayOfString[868] = "CRIB";
    arrayOfString[869] = "CROW";
    arrayOfString[870] = "CRUD";
    arrayOfString[871] = "CUBA";
    arrayOfString[872] = "CUBE";
    arrayOfString[873] = "CUFF";
    arrayOfString[874] = "CULL";
    arrayOfString[875] = "CULT";
    arrayOfString[876] = "CUNY";
    arrayOfString[877] = "CURB";
    arrayOfString[878] = "CURD";
    arrayOfString[879] = "CURE";
    arrayOfString[880] = "CURL";
    arrayOfString[881] = "CURT";
    arrayOfString[882] = "CUTS";
    arrayOfString[883] = "DADE";
    arrayOfString[884] = "DALE";
    arrayOfString[885] = "DAME";
    arrayOfString[886] = "DANA";
    arrayOfString[887] = "DANE";
    arrayOfString[888] = "DANG";
    arrayOfString[889] = "DANK";
    arrayOfString[890] = "DARE";
    arrayOfString[891] = "DARK";
    arrayOfString[892] = "DARN";
    arrayOfString[893] = "DART";
    arrayOfString[894] = "DASH";
    arrayOfString[895] = "DATA";
    arrayOfString[896] = "DATE";
    arrayOfString[897] = "DAVE";
    arrayOfString[898] = "DAVY";
    arrayOfString[899] = "DAWN";
    arrayOfString[900] = "DAYS";
    arrayOfString[901] = "DEAD";
    arrayOfString[902] = "DEAF";
    arrayOfString[903] = "DEAL";
    arrayOfString[904] = "DEAN";
    arrayOfString[905] = "DEAR";
    arrayOfString[906] = "DEBT";
    arrayOfString[907] = "DECK";
    arrayOfString[908] = "DEED";
    arrayOfString[909] = "DEEM";
    arrayOfString[910] = "DEER";
    arrayOfString[911] = "DEFT";
    arrayOfString[912] = "DEFY";
    arrayOfString[913] = "DELL";
    arrayOfString[914] = "DENT";
    arrayOfString[915] = "DENY";
    arrayOfString[916] = "DESK";
    arrayOfString[917] = "DIAL";
    arrayOfString[918] = "DICE";
    arrayOfString[919] = "DIED";
    arrayOfString[920] = "DIET";
    arrayOfString[921] = "DIME";
    arrayOfString[922] = "DINE";
    arrayOfString[923] = "DING";
    arrayOfString[924] = "DINT";
    arrayOfString[925] = "DIRE";
    arrayOfString[926] = "DIRT";
    arrayOfString[927] = "DISC";
    arrayOfString[928] = "DISH";
    arrayOfString[929] = "DISK";
    arrayOfString[930] = "DIVE";
    arrayOfString[931] = "DOCK";
    arrayOfString[932] = "DOES";
    arrayOfString[933] = "DOLE";
    arrayOfString[934] = "DOLL";
    arrayOfString[935] = "DOLT";
    arrayOfString[936] = "DOME";
    arrayOfString[937] = "DONE";
    arrayOfString[938] = "DOOM";
    arrayOfString[939] = "DOOR";
    arrayOfString[940] = "DORA";
    arrayOfString[941] = "DOSE";
    arrayOfString[942] = "DOTE";
    arrayOfString[943] = "DOUG";
    arrayOfString[944] = "DOUR";
    arrayOfString[945] = "DOVE";
    arrayOfString[946] = "DOWN";
    arrayOfString[947] = "DRAB";
    arrayOfString[948] = "DRAG";
    arrayOfString[949] = "DRAM";
    arrayOfString[950] = "DRAW";
    arrayOfString[951] = "DREW";
    arrayOfString[952] = "DRUB";
    arrayOfString[953] = "DRUG";
    arrayOfString[954] = "DRUM";
    arrayOfString[955] = "DUAL";
    arrayOfString[956] = "DUCK";
    arrayOfString[957] = "DUCT";
    arrayOfString[958] = "DUEL";
    arrayOfString[959] = "DUET";
    arrayOfString[960] = "DUKE";
    arrayOfString[961] = "DULL";
    arrayOfString[962] = "DUMB";
    arrayOfString[963] = "DUNE";
    arrayOfString[964] = "DUNK";
    arrayOfString[965] = "DUSK";
    arrayOfString[966] = "DUST";
    arrayOfString[967] = "DUTY";
    arrayOfString[968] = "EACH";
    arrayOfString[969] = "EARL";
    arrayOfString[970] = "EARN";
    arrayOfString[971] = "EASE";
    arrayOfString[972] = "EAST";
    arrayOfString[973] = "EASY";
    arrayOfString[974] = "EBEN";
    arrayOfString[975] = "ECHO";
    arrayOfString[976] = "EDDY";
    arrayOfString[977] = "EDEN";
    arrayOfString[978] = "EDGE";
    arrayOfString[979] = "EDGY";
    arrayOfString[980] = "EDIT";
    arrayOfString[981] = "EDNA";
    arrayOfString[982] = "EGAN";
    arrayOfString[983] = "ELAN";
    arrayOfString[984] = "ELBA";
    arrayOfString[985] = "ELLA";
    arrayOfString[986] = "ELSE";
    arrayOfString[987] = "EMIL";
    arrayOfString[988] = "EMIT";
    arrayOfString[989] = "EMMA";
    arrayOfString[990] = "ENDS";
    arrayOfString[991] = "ERIC";
    arrayOfString[992] = "EROS";
    arrayOfString[993] = "EVEN";
    arrayOfString[994] = "EVER";
    arrayOfString[995] = "EVIL";
    arrayOfString[996] = "EYED";
    arrayOfString[997] = "FACE";
    arrayOfString[998] = "FACT";
    arrayOfString[999] = "FADE";
    arrayOfString[1000] = "FAIL";
    arrayOfString[1001] = "FAIN";
    arrayOfString[1002] = "FAIR";
    arrayOfString[1003] = "FAKE";
    arrayOfString[1004] = "FALL";
    arrayOfString[1005] = "FAME";
    arrayOfString[1006] = "FANG";
    arrayOfString[1007] = "FARM";
    arrayOfString[1008] = "FAST";
    arrayOfString[1009] = "FATE";
    arrayOfString[1010] = "FAWN";
    arrayOfString[1011] = "FEAR";
    arrayOfString[1012] = "FEAT";
    arrayOfString[1013] = "FEED";
    arrayOfString[1014] = "FEEL";
    arrayOfString[1015] = "FEET";
    arrayOfString[1016] = "FELL";
    arrayOfString[1017] = "FELT";
    arrayOfString[1018] = "FEND";
    arrayOfString[1019] = "FERN";
    arrayOfString[1020] = "FEST";
    arrayOfString[1021] = "FEUD";
    arrayOfString[1022] = "FIEF";
    arrayOfString[1023] = "FIGS";
    arrayOfString[1024] = "FILE";
    arrayOfString[1025] = "FILL";
    arrayOfString[1026] = "FILM";
    arrayOfString[1027] = "FIND";
    arrayOfString[1028] = "FINE";
    arrayOfString[1029] = "FINK";
    arrayOfString[1030] = "FIRE";
    arrayOfString[1031] = "FIRM";
    arrayOfString[1032] = "FISH";
    arrayOfString[1033] = "FISK";
    arrayOfString[1034] = "FIST";
    arrayOfString[1035] = "FITS";
    arrayOfString[1036] = "FIVE";
    arrayOfString[1037] = "FLAG";
    arrayOfString[1038] = "FLAK";
    arrayOfString[1039] = "FLAM";
    arrayOfString[1040] = "FLAT";
    arrayOfString[1041] = "FLAW";
    arrayOfString[1042] = "FLEA";
    arrayOfString[1043] = "FLED";
    arrayOfString[1044] = "FLEW";
    arrayOfString[1045] = "FLIT";
    arrayOfString[1046] = "FLOC";
    arrayOfString[1047] = "FLOG";
    arrayOfString[1048] = "FLOW";
    arrayOfString[1049] = "FLUB";
    arrayOfString[1050] = "FLUE";
    arrayOfString[1051] = "FOAL";
    arrayOfString[1052] = "FOAM";
    arrayOfString[1053] = "FOGY";
    arrayOfString[1054] = "FOIL";
    arrayOfString[1055] = "FOLD";
    arrayOfString[1056] = "FOLK";
    arrayOfString[1057] = "FOND";
    arrayOfString[1058] = "FONT";
    arrayOfString[1059] = "FOOD";
    arrayOfString[1060] = "FOOL";
    arrayOfString[1061] = "FOOT";
    arrayOfString[1062] = "FORD";
    arrayOfString[1063] = "FORE";
    arrayOfString[1064] = "FORK";
    arrayOfString[1065] = "FORM";
    arrayOfString[1066] = "FORT";
    arrayOfString[1067] = "FOSS";
    arrayOfString[1068] = "FOUL";
    arrayOfString[1069] = "FOUR";
    arrayOfString[1070] = "FOWL";
    arrayOfString[1071] = "FRAU";
    arrayOfString[1072] = "FRAY";
    arrayOfString[1073] = "FRED";
    arrayOfString[1074] = "FREE";
    arrayOfString[1075] = "FRET";
    arrayOfString[1076] = "FREY";
    arrayOfString[1077] = "FROG";
    arrayOfString[1078] = "FROM";
    arrayOfString[1079] = "FUEL";
    arrayOfString[1080] = "FULL";
    arrayOfString[1081] = "FUME";
    arrayOfString[1082] = "FUND";
    arrayOfString[1083] = "FUNK";
    arrayOfString[1084] = "FURY";
    arrayOfString[1085] = "FUSE";
    arrayOfString[1086] = "FUSS";
    arrayOfString[1087] = "GAFF";
    arrayOfString[1088] = "GAGE";
    arrayOfString[1089] = "GAIL";
    arrayOfString[1090] = "GAIN";
    arrayOfString[1091] = "GAIT";
    arrayOfString[1092] = "GALA";
    arrayOfString[1093] = "GALE";
    arrayOfString[1094] = "GALL";
    arrayOfString[1095] = "GALT";
    arrayOfString[1096] = "GAME";
    arrayOfString[1097] = "GANG";
    arrayOfString[1098] = "GARB";
    arrayOfString[1099] = "GARY";
    arrayOfString[1100] = "GASH";
    arrayOfString[1101] = "GATE";
    arrayOfString[1102] = "GAUL";
    arrayOfString[1103] = "GAUR";
    arrayOfString[1104] = "GAVE";
    arrayOfString[1105] = "GAWK";
    arrayOfString[1106] = "GEAR";
    arrayOfString[1107] = "GELD";
    arrayOfString[1108] = "GENE";
    arrayOfString[1109] = "GENT";
    arrayOfString[1110] = "GERM";
    arrayOfString[1111] = "GETS";
    arrayOfString[1112] = "GIBE";
    arrayOfString[1113] = "GIFT";
    arrayOfString[1114] = "GILD";
    arrayOfString[1115] = "GILL";
    arrayOfString[1116] = "GILT";
    arrayOfString[1117] = "GINA";
    arrayOfString[1118] = "GIRD";
    arrayOfString[1119] = "GIRL";
    arrayOfString[1120] = "GIST";
    arrayOfString[1121] = "GIVE";
    arrayOfString[1122] = "GLAD";
    arrayOfString[1123] = "GLEE";
    arrayOfString[1124] = "GLEN";
    arrayOfString[1125] = "GLIB";
    arrayOfString[1126] = "GLOB";
    arrayOfString[1127] = "GLOM";
    arrayOfString[1128] = "GLOW";
    arrayOfString[1129] = "GLUE";
    arrayOfString[1130] = "GLUM";
    arrayOfString[1131] = "GLUT";
    arrayOfString[1132] = "GOAD";
    arrayOfString[1133] = "GOAL";
    arrayOfString[1134] = "GOAT";
    arrayOfString[1135] = "GOER";
    arrayOfString[1136] = "GOES";
    arrayOfString[1137] = "GOLD";
    arrayOfString[1138] = "GOLF";
    arrayOfString[1139] = "GONE";
    arrayOfString[1140] = "GONG";
    arrayOfString[1141] = "GOOD";
    arrayOfString[1142] = "GOOF";
    arrayOfString[1143] = "GORE";
    arrayOfString[1144] = "GORY";
    arrayOfString[1145] = "GOSH";
    arrayOfString[1146] = "GOUT";
    arrayOfString[1147] = "GOWN";
    arrayOfString[1148] = "GRAB";
    arrayOfString[1149] = "GRAD";
    arrayOfString[1150] = "GRAY";
    arrayOfString[1151] = "GREG";
    arrayOfString[1152] = "GREW";
    arrayOfString[1153] = "GREY";
    arrayOfString[1154] = "GRID";
    arrayOfString[1155] = "GRIM";
    arrayOfString[1156] = "GRIN";
    arrayOfString[1157] = "GRIT";
    arrayOfString[1158] = "GROW";
    arrayOfString[1159] = "GRUB";
    arrayOfString[1160] = "GULF";
    arrayOfString[1161] = "GULL";
    arrayOfString[1162] = "GUNK";
    arrayOfString[1163] = "GURU";
    arrayOfString[1164] = "GUSH";
    arrayOfString[1165] = "GUST";
    arrayOfString[1166] = "GWEN";
    arrayOfString[1167] = "GWYN";
    arrayOfString[1168] = "HAAG";
    arrayOfString[1169] = "HAAS";
    arrayOfString[1170] = "HACK";
    arrayOfString[1171] = "HAIL";
    arrayOfString[1172] = "HAIR";
    arrayOfString[1173] = "HALE";
    arrayOfString[1174] = "HALF";
    arrayOfString[1175] = "HALL";
    arrayOfString[1176] = "HALO";
    arrayOfString[1177] = "HALT";
    arrayOfString[1178] = "HAND";
    arrayOfString[1179] = "HANG";
    arrayOfString[1180] = "HANK";
    arrayOfString[1181] = "HANS";
    arrayOfString[1182] = "HARD";
    arrayOfString[1183] = "HARK";
    arrayOfString[1184] = "HARM";
    arrayOfString[1185] = "HART";
    arrayOfString[1186] = "HASH";
    arrayOfString[1187] = "HAST";
    arrayOfString[1188] = "HATE";
    arrayOfString[1189] = "HATH";
    arrayOfString[1190] = "HAUL";
    arrayOfString[1191] = "HAVE";
    arrayOfString[1192] = "HAWK";
    arrayOfString[1193] = "HAYS";
    arrayOfString[1194] = "HEAD";
    arrayOfString[1195] = "HEAL";
    arrayOfString[1196] = "HEAR";
    arrayOfString[1197] = "HEAT";
    arrayOfString[1198] = "HEBE";
    arrayOfString[1199] = "HECK";
    arrayOfString[1200] = "HEED";
    arrayOfString[1201] = "HEEL";
    arrayOfString[1202] = "HEFT";
    arrayOfString[1203] = "HELD";
    arrayOfString[1204] = "HELL";
    arrayOfString[1205] = "HELM";
    arrayOfString[1206] = "HERB";
    arrayOfString[1207] = "HERD";
    arrayOfString[1208] = "HERE";
    arrayOfString[1209] = "HERO";
    arrayOfString[1210] = "HERS";
    arrayOfString[1211] = "HESS";
    arrayOfString[1212] = "HEWN";
    arrayOfString[1213] = "HICK";
    arrayOfString[1214] = "HIDE";
    arrayOfString[1215] = "HIGH";
    arrayOfString[1216] = "HIKE";
    arrayOfString[1217] = "HILL";
    arrayOfString[1218] = "HILT";
    arrayOfString[1219] = "HIND";
    arrayOfString[1220] = "HINT";
    arrayOfString[1221] = "HIRE";
    arrayOfString[1222] = "HISS";
    arrayOfString[1223] = "HIVE";
    arrayOfString[1224] = "HOBO";
    arrayOfString[1225] = "HOCK";
    arrayOfString[1226] = "HOFF";
    arrayOfString[1227] = "HOLD";
    arrayOfString[1228] = "HOLE";
    arrayOfString[1229] = "HOLM";
    arrayOfString[1230] = "HOLT";
    arrayOfString[1231] = "HOME";
    arrayOfString[1232] = "HONE";
    arrayOfString[1233] = "HONK";
    arrayOfString[1234] = "HOOD";
    arrayOfString[1235] = "HOOF";
    arrayOfString[1236] = "HOOK";
    arrayOfString[1237] = "HOOT";
    arrayOfString[1238] = "HORN";
    arrayOfString[1239] = "HOSE";
    arrayOfString[1240] = "HOST";
    arrayOfString[1241] = "HOUR";
    arrayOfString[1242] = "HOVE";
    arrayOfString[1243] = "HOWE";
    arrayOfString[1244] = "HOWL";
    arrayOfString[1245] = "HOYT";
    arrayOfString[1246] = "HUCK";
    arrayOfString[1247] = "HUED";
    arrayOfString[1248] = "HUFF";
    arrayOfString[1249] = "HUGE";
    arrayOfString[1250] = "HUGH";
    arrayOfString[1251] = "HUGO";
    arrayOfString[1252] = "HULK";
    arrayOfString[1253] = "HULL";
    arrayOfString[1254] = "HUNK";
    arrayOfString[1255] = "HUNT";
    arrayOfString[1256] = "HURD";
    arrayOfString[1257] = "HURL";
    arrayOfString[1258] = "HURT";
    arrayOfString[1259] = "HUSH";
    arrayOfString[1260] = "HYDE";
    arrayOfString[1261] = "HYMN";
    arrayOfString[1262] = "IBIS";
    arrayOfString[1263] = "ICON";
    arrayOfString[1264] = "IDEA";
    arrayOfString[1265] = "IDLE";
    arrayOfString[1266] = "IFFY";
    arrayOfString[1267] = "INCA";
    arrayOfString[1268] = "INCH";
    arrayOfString[1269] = "INTO";
    arrayOfString[1270] = "IONS";
    arrayOfString[1271] = "IOTA";
    arrayOfString[1272] = "IOWA";
    arrayOfString[1273] = "IRIS";
    arrayOfString[1274] = "IRMA";
    arrayOfString[1275] = "IRON";
    arrayOfString[1276] = "ISLE";
    arrayOfString[1277] = "ITCH";
    arrayOfString[1278] = "ITEM";
    arrayOfString[1279] = "IVAN";
    arrayOfString[1280] = "JACK";
    arrayOfString[1281] = "JADE";
    arrayOfString[1282] = "JAIL";
    arrayOfString[1283] = "JAKE";
    arrayOfString[1284] = "JANE";
    arrayOfString[1285] = "JAVA";
    arrayOfString[1286] = "JEAN";
    arrayOfString[1287] = "JEFF";
    arrayOfString[1288] = "JERK";
    arrayOfString[1289] = "JESS";
    arrayOfString[1290] = "JEST";
    arrayOfString[1291] = "JIBE";
    arrayOfString[1292] = "JILL";
    arrayOfString[1293] = "JILT";
    arrayOfString[1294] = "JIVE";
    arrayOfString[1295] = "JOAN";
    arrayOfString[1296] = "JOBS";
    arrayOfString[1297] = "JOCK";
    arrayOfString[1298] = "JOEL";
    arrayOfString[1299] = "JOEY";
    arrayOfString[1300] = "JOHN";
    arrayOfString[1301] = "JOIN";
    arrayOfString[1302] = "JOKE";
    arrayOfString[1303] = "JOLT";
    arrayOfString[1304] = "JOVE";
    arrayOfString[1305] = "JUDD";
    arrayOfString[1306] = "JUDE";
    arrayOfString[1307] = "JUDO";
    arrayOfString[1308] = "JUDY";
    arrayOfString[1309] = "JUJU";
    arrayOfString[1310] = "JUKE";
    arrayOfString[1311] = "JULY";
    arrayOfString[1312] = "JUNE";
    arrayOfString[1313] = "JUNK";
    arrayOfString[1314] = "JUNO";
    arrayOfString[1315] = "JURY";
    arrayOfString[1316] = "JUST";
    arrayOfString[1317] = "JUTE";
    arrayOfString[1318] = "KAHN";
    arrayOfString[1319] = "KALE";
    arrayOfString[1320] = "KANE";
    arrayOfString[1321] = "KANT";
    arrayOfString[1322] = "KARL";
    arrayOfString[1323] = "KATE";
    arrayOfString[1324] = "KEEL";
    arrayOfString[1325] = "KEEN";
    arrayOfString[1326] = "KENO";
    arrayOfString[1327] = "KENT";
    arrayOfString[1328] = "KERN";
    arrayOfString[1329] = "KERR";
    arrayOfString[1330] = "KEYS";
    arrayOfString[1331] = "KICK";
    arrayOfString[1332] = "KILL";
    arrayOfString[1333] = "KIND";
    arrayOfString[1334] = "KING";
    arrayOfString[1335] = "KIRK";
    arrayOfString[1336] = "KISS";
    arrayOfString[1337] = "KITE";
    arrayOfString[1338] = "KLAN";
    arrayOfString[1339] = "KNEE";
    arrayOfString[1340] = "KNEW";
    arrayOfString[1341] = "KNIT";
    arrayOfString[1342] = "KNOB";
    arrayOfString[1343] = "KNOT";
    arrayOfString[1344] = "KNOW";
    arrayOfString[1345] = "KOCH";
    arrayOfString[1346] = "KONG";
    arrayOfString[1347] = "KUDO";
    arrayOfString[1348] = "KURD";
    arrayOfString[1349] = "KURT";
    arrayOfString[1350] = "KYLE";
    arrayOfString[1351] = "LACE";
    arrayOfString[1352] = "LACK";
    arrayOfString[1353] = "LACY";
    arrayOfString[1354] = "LADY";
    arrayOfString[1355] = "LAID";
    arrayOfString[1356] = "LAIN";
    arrayOfString[1357] = "LAIR";
    arrayOfString[1358] = "LAKE";
    arrayOfString[1359] = "LAMB";
    arrayOfString[1360] = "LAME";
    arrayOfString[1361] = "LAND";
    arrayOfString[1362] = "LANE";
    arrayOfString[1363] = "LANG";
    arrayOfString[1364] = "LARD";
    arrayOfString[1365] = "LARK";
    arrayOfString[1366] = "LASS";
    arrayOfString[1367] = "LAST";
    arrayOfString[1368] = "LATE";
    arrayOfString[1369] = "LAUD";
    arrayOfString[1370] = "LAVA";
    arrayOfString[1371] = "LAWN";
    arrayOfString[1372] = "LAWS";
    arrayOfString[1373] = "LAYS";
    arrayOfString[1374] = "LEAD";
    arrayOfString[1375] = "LEAF";
    arrayOfString[1376] = "LEAK";
    arrayOfString[1377] = "LEAN";
    arrayOfString[1378] = "LEAR";
    arrayOfString[1379] = "LEEK";
    arrayOfString[1380] = "LEER";
    arrayOfString[1381] = "LEFT";
    arrayOfString[1382] = "LEND";
    arrayOfString[1383] = "LENS";
    arrayOfString[1384] = "LENT";
    arrayOfString[1385] = "LEON";
    arrayOfString[1386] = "LESK";
    arrayOfString[1387] = "LESS";
    arrayOfString[1388] = "LEST";
    arrayOfString[1389] = "LETS";
    arrayOfString[1390] = "LIAR";
    arrayOfString[1391] = "LICE";
    arrayOfString[1392] = "LICK";
    arrayOfString[1393] = "LIED";
    arrayOfString[1394] = "LIEN";
    arrayOfString[1395] = "LIES";
    arrayOfString[1396] = "LIEU";
    arrayOfString[1397] = "LIFE";
    arrayOfString[1398] = "LIFT";
    arrayOfString[1399] = "LIKE";
    arrayOfString[1400] = "LILA";
    arrayOfString[1401] = "LILT";
    arrayOfString[1402] = "LILY";
    arrayOfString[1403] = "LIMA";
    arrayOfString[1404] = "LIMB";
    arrayOfString[1405] = "LIME";
    arrayOfString[1406] = "LIND";
    arrayOfString[1407] = "LINE";
    arrayOfString[1408] = "LINK";
    arrayOfString[1409] = "LINT";
    arrayOfString[1410] = "LION";
    arrayOfString[1411] = "LISA";
    arrayOfString[1412] = "LIST";
    arrayOfString[1413] = "LIVE";
    arrayOfString[1414] = "LOAD";
    arrayOfString[1415] = "LOAF";
    arrayOfString[1416] = "LOAM";
    arrayOfString[1417] = "LOAN";
    arrayOfString[1418] = "LOCK";
    arrayOfString[1419] = "LOFT";
    arrayOfString[1420] = "LOGE";
    arrayOfString[1421] = "LOIS";
    arrayOfString[1422] = "LOLA";
    arrayOfString[1423] = "LONE";
    arrayOfString[1424] = "LONG";
    arrayOfString[1425] = "LOOK";
    arrayOfString[1426] = "LOON";
    arrayOfString[1427] = "LOOT";
    arrayOfString[1428] = "LORD";
    arrayOfString[1429] = "LORE";
    arrayOfString[1430] = "LOSE";
    arrayOfString[1431] = "LOSS";
    arrayOfString[1432] = "LOST";
    arrayOfString[1433] = "LOUD";
    arrayOfString[1434] = "LOVE";
    arrayOfString[1435] = "LOWE";
    arrayOfString[1436] = "LUCK";
    arrayOfString[1437] = "LUCY";
    arrayOfString[1438] = "LUGE";
    arrayOfString[1439] = "LUKE";
    arrayOfString[1440] = "LULU";
    arrayOfString[1441] = "LUND";
    arrayOfString[1442] = "LUNG";
    arrayOfString[1443] = "LURA";
    arrayOfString[1444] = "LURE";
    arrayOfString[1445] = "LURK";
    arrayOfString[1446] = "LUSH";
    arrayOfString[1447] = "LUST";
    arrayOfString[1448] = "LYLE";
    arrayOfString[1449] = "LYNN";
    arrayOfString[1450] = "LYON";
    arrayOfString[1451] = "LYRA";
    arrayOfString[1452] = "MACE";
    arrayOfString[1453] = "MADE";
    arrayOfString[1454] = "MAGI";
    arrayOfString[1455] = "MAID";
    arrayOfString[1456] = "MAIL";
    arrayOfString[1457] = "MAIN";
    arrayOfString[1458] = "MAKE";
    arrayOfString[1459] = "MALE";
    arrayOfString[1460] = "MALI";
    arrayOfString[1461] = "MALL";
    arrayOfString[1462] = "MALT";
    arrayOfString[1463] = "MANA";
    arrayOfString[1464] = "MANN";
    arrayOfString[1465] = "MANY";
    arrayOfString[1466] = "MARC";
    arrayOfString[1467] = "MARE";
    arrayOfString[1468] = "MARK";
    arrayOfString[1469] = "MARS";
    arrayOfString[1470] = "MART";
    arrayOfString[1471] = "MARY";
    arrayOfString[1472] = "MASH";
    arrayOfString[1473] = "MASK";
    arrayOfString[1474] = "MASS";
    arrayOfString[1475] = "MAST";
    arrayOfString[1476] = "MATE";
    arrayOfString[1477] = "MATH";
    arrayOfString[1478] = "MAUL";
    arrayOfString[1479] = "MAYO";
    arrayOfString[1480] = "MEAD";
    arrayOfString[1481] = "MEAL";
    arrayOfString[1482] = "MEAN";
    arrayOfString[1483] = "MEAT";
    arrayOfString[1484] = "MEEK";
    arrayOfString[1485] = "MEET";
    arrayOfString[1486] = "MELD";
    arrayOfString[1487] = "MELT";
    arrayOfString[1488] = "MEMO";
    arrayOfString[1489] = "MEND";
    arrayOfString[1490] = "MENU";
    arrayOfString[1491] = "MERT";
    arrayOfString[1492] = "MESH";
    arrayOfString[1493] = "MESS";
    arrayOfString[1494] = "MICE";
    arrayOfString[1495] = "MIKE";
    arrayOfString[1496] = "MILD";
    arrayOfString[1497] = "MILE";
    arrayOfString[1498] = "MILK";
    arrayOfString[1499] = "MILL";
    arrayOfString[1500] = "MILT";
    arrayOfString[1501] = "MIMI";
    arrayOfString[1502] = "MIND";
    arrayOfString[1503] = "MINE";
    arrayOfString[1504] = "MINI";
    arrayOfString[1505] = "MINK";
    arrayOfString[1506] = "MINT";
    arrayOfString[1507] = "MIRE";
    arrayOfString[1508] = "MISS";
    arrayOfString[1509] = "MIST";
    arrayOfString[1510] = "MITE";
    arrayOfString[1511] = "MITT";
    arrayOfString[1512] = "MOAN";
    arrayOfString[1513] = "MOAT";
    arrayOfString[1514] = "MOCK";
    arrayOfString[1515] = "MODE";
    arrayOfString[1516] = "MOLD";
    arrayOfString[1517] = "MOLE";
    arrayOfString[1518] = "MOLL";
    arrayOfString[1519] = "MOLT";
    arrayOfString[1520] = "MONA";
    arrayOfString[1521] = "MONK";
    arrayOfString[1522] = "MONT";
    arrayOfString[1523] = "MOOD";
    arrayOfString[1524] = "MOON";
    arrayOfString[1525] = "MOOR";
    arrayOfString[1526] = "MOOT";
    arrayOfString[1527] = "MORE";
    arrayOfString[1528] = "MORN";
    arrayOfString[1529] = "MORT";
    arrayOfString[1530] = "MOSS";
    arrayOfString[1531] = "MOST";
    arrayOfString[1532] = "MOTH";
    arrayOfString[1533] = "MOVE";
    arrayOfString[1534] = "MUCH";
    arrayOfString[1535] = "MUCK";
    arrayOfString[1536] = "MUDD";
    arrayOfString[1537] = "MUFF";
    arrayOfString[1538] = "MULE";
    arrayOfString[1539] = "MULL";
    arrayOfString[1540] = "MURK";
    arrayOfString[1541] = "MUSH";
    arrayOfString[1542] = "MUST";
    arrayOfString[1543] = "MUTE";
    arrayOfString[1544] = "MUTT";
    arrayOfString[1545] = "MYRA";
    arrayOfString[1546] = "MYTH";
    arrayOfString[1547] = "NAGY";
    arrayOfString[1548] = "NAIL";
    arrayOfString[1549] = "NAIR";
    arrayOfString[1550] = "NAME";
    arrayOfString[1551] = "NARY";
    arrayOfString[1552] = "NASH";
    arrayOfString[1553] = "NAVE";
    arrayOfString[1554] = "NAVY";
    arrayOfString[1555] = "NEAL";
    arrayOfString[1556] = "NEAR";
    arrayOfString[1557] = "NEAT";
    arrayOfString[1558] = "NECK";
    arrayOfString[1559] = "NEED";
    arrayOfString[1560] = "NEIL";
    arrayOfString[1561] = "NELL";
    arrayOfString[1562] = "NEON";
    arrayOfString[1563] = "NERO";
    arrayOfString[1564] = "NESS";
    arrayOfString[1565] = "NEST";
    arrayOfString[1566] = "NEWS";
    arrayOfString[1567] = "NEWT";
    arrayOfString[1568] = "NIBS";
    arrayOfString[1569] = "NICE";
    arrayOfString[1570] = "NICK";
    arrayOfString[1571] = "NILE";
    arrayOfString[1572] = "NINA";
    arrayOfString[1573] = "NINE";
    arrayOfString[1574] = "NOAH";
    arrayOfString[1575] = "NODE";
    arrayOfString[1576] = "NOEL";
    arrayOfString[1577] = "NOLL";
    arrayOfString[1578] = "NONE";
    arrayOfString[1579] = "NOOK";
    arrayOfString[1580] = "NOON";
    arrayOfString[1581] = "NORM";
    arrayOfString[1582] = "NOSE";
    arrayOfString[1583] = "NOTE";
    arrayOfString[1584] = "NOUN";
    arrayOfString[1585] = "NOVA";
    arrayOfString[1586] = "NUDE";
    arrayOfString[1587] = "NULL";
    arrayOfString[1588] = "NUMB";
    arrayOfString[1589] = "OATH";
    arrayOfString[1590] = "OBEY";
    arrayOfString[1591] = "OBOE";
    arrayOfString[1592] = "ODIN";
    arrayOfString[1593] = "OHIO";
    arrayOfString[1594] = "OILY";
    arrayOfString[1595] = "OINT";
    arrayOfString[1596] = "OKAY";
    arrayOfString[1597] = "OLAF";
    arrayOfString[1598] = "OLDY";
    arrayOfString[1599] = "OLGA";
    arrayOfString[1600] = "OLIN";
    arrayOfString[1601] = "OMAN";
    arrayOfString[1602] = "OMEN";
    arrayOfString[1603] = "OMIT";
    arrayOfString[1604] = "ONCE";
    arrayOfString[1605] = "ONES";
    arrayOfString[1606] = "ONLY";
    arrayOfString[1607] = "ONTO";
    arrayOfString[1608] = "ONUS";
    arrayOfString[1609] = "ORAL";
    arrayOfString[1610] = "ORGY";
    arrayOfString[1611] = "OSLO";
    arrayOfString[1612] = "OTIS";
    arrayOfString[1613] = "OTTO";
    arrayOfString[1614] = "OUCH";
    arrayOfString[1615] = "OUST";
    arrayOfString[1616] = "OUTS";
    arrayOfString[1617] = "OVAL";
    arrayOfString[1618] = "OVEN";
    arrayOfString[1619] = "OVER";
    arrayOfString[1620] = "OWLY";
    arrayOfString[1621] = "OWNS";
    arrayOfString[1622] = "QUAD";
    arrayOfString[1623] = "QUIT";
    arrayOfString[1624] = "QUOD";
    arrayOfString[1625] = "RACE";
    arrayOfString[1626] = "RACK";
    arrayOfString[1627] = "RACY";
    arrayOfString[1628] = "RAFT";
    arrayOfString[1629] = "RAGE";
    arrayOfString[1630] = "RAID";
    arrayOfString[1631] = "RAIL";
    arrayOfString[1632] = "RAIN";
    arrayOfString[1633] = "RAKE";
    arrayOfString[1634] = "RANK";
    arrayOfString[1635] = "RANT";
    arrayOfString[1636] = "RARE";
    arrayOfString[1637] = "RASH";
    arrayOfString[1638] = "RATE";
    arrayOfString[1639] = "RAVE";
    arrayOfString[1640] = "RAYS";
    arrayOfString[1641] = "READ";
    arrayOfString[1642] = "REAL";
    arrayOfString[1643] = "REAM";
    arrayOfString[1644] = "REAR";
    arrayOfString[1645] = "RECK";
    arrayOfString[1646] = "REED";
    arrayOfString[1647] = "REEF";
    arrayOfString[1648] = "REEK";
    arrayOfString[1649] = "REEL";
    arrayOfString[1650] = "REID";
    arrayOfString[1651] = "REIN";
    arrayOfString[1652] = "RENA";
    arrayOfString[1653] = "REND";
    arrayOfString[1654] = "RENT";
    arrayOfString[1655] = "REST";
    arrayOfString[1656] = "RICE";
    arrayOfString[1657] = "RICH";
    arrayOfString[1658] = "RICK";
    arrayOfString[1659] = "RIDE";
    arrayOfString[1660] = "RIFT";
    arrayOfString[1661] = "RILL";
    arrayOfString[1662] = "RIME";
    arrayOfString[1663] = "RING";
    arrayOfString[1664] = "RINK";
    arrayOfString[1665] = "RISE";
    arrayOfString[1666] = "RISK";
    arrayOfString[1667] = "RITE";
    arrayOfString[1668] = "ROAD";
    arrayOfString[1669] = "ROAM";
    arrayOfString[1670] = "ROAR";
    arrayOfString[1671] = "ROBE";
    arrayOfString[1672] = "ROCK";
    arrayOfString[1673] = "RODE";
    arrayOfString[1674] = "ROIL";
    arrayOfString[1675] = "ROLL";
    arrayOfString[1676] = "ROME";
    arrayOfString[1677] = "ROOD";
    arrayOfString[1678] = "ROOF";
    arrayOfString[1679] = "ROOK";
    arrayOfString[1680] = "ROOM";
    arrayOfString[1681] = "ROOT";
    arrayOfString[1682] = "ROSA";
    arrayOfString[1683] = "ROSE";
    arrayOfString[1684] = "ROSS";
    arrayOfString[1685] = "ROSY";
    arrayOfString[1686] = "ROTH";
    arrayOfString[1687] = "ROUT";
    arrayOfString[1688] = "ROVE";
    arrayOfString[1689] = "ROWE";
    arrayOfString[1690] = "ROWS";
    arrayOfString[1691] = "RUBE";
    arrayOfString[1692] = "RUBY";
    arrayOfString[1693] = "RUDE";
    arrayOfString[1694] = "RUDY";
    arrayOfString[1695] = "RUIN";
    arrayOfString[1696] = "RULE";
    arrayOfString[1697] = "RUNG";
    arrayOfString[1698] = "RUNS";
    arrayOfString[1699] = "RUNT";
    arrayOfString[1700] = "RUSE";
    arrayOfString[1701] = "RUSH";
    arrayOfString[1702] = "RUSK";
    arrayOfString[1703] = "RUSS";
    arrayOfString[1704] = "RUST";
    arrayOfString[1705] = "RUTH";
    arrayOfString[1706] = "SACK";
    arrayOfString[1707] = "SAFE";
    arrayOfString[1708] = "SAGE";
    arrayOfString[1709] = "SAID";
    arrayOfString[1710] = "SAIL";
    arrayOfString[1711] = "SALE";
    arrayOfString[1712] = "SALK";
    arrayOfString[1713] = "SALT";
    arrayOfString[1714] = "SAME";
    arrayOfString[1715] = "SAND";
    arrayOfString[1716] = "SANE";
    arrayOfString[1717] = "SANG";
    arrayOfString[1718] = "SANK";
    arrayOfString[1719] = "SARA";
    arrayOfString[1720] = "SAUL";
    arrayOfString[1721] = "SAVE";
    arrayOfString[1722] = "SAYS";
    arrayOfString[1723] = "SCAN";
    arrayOfString[1724] = "SCAR";
    arrayOfString[1725] = "SCAT";
    arrayOfString[1726] = "SCOT";
    arrayOfString[1727] = "SEAL";
    arrayOfString[1728] = "SEAM";
    arrayOfString[1729] = "SEAR";
    arrayOfString[1730] = "SEAT";
    arrayOfString[1731] = "SEED";
    arrayOfString[1732] = "SEEK";
    arrayOfString[1733] = "SEEM";
    arrayOfString[1734] = "SEEN";
    arrayOfString[1735] = "SEES";
    arrayOfString[1736] = "SELF";
    arrayOfString[1737] = "SELL";
    arrayOfString[1738] = "SEND";
    arrayOfString[1739] = "SENT";
    arrayOfString[1740] = "SETS";
    arrayOfString[1741] = "SEWN";
    arrayOfString[1742] = "SHAG";
    arrayOfString[1743] = "SHAM";
    arrayOfString[1744] = "SHAW";
    arrayOfString[1745] = "SHAY";
    arrayOfString[1746] = "SHED";
    arrayOfString[1747] = "SHIM";
    arrayOfString[1748] = "SHIN";
    arrayOfString[1749] = "SHOD";
    arrayOfString[1750] = "SHOE";
    arrayOfString[1751] = "SHOT";
    arrayOfString[1752] = "SHOW";
    arrayOfString[1753] = "SHUN";
    arrayOfString[1754] = "SHUT";
    arrayOfString[1755] = "SICK";
    arrayOfString[1756] = "SIDE";
    arrayOfString[1757] = "SIFT";
    arrayOfString[1758] = "SIGH";
    arrayOfString[1759] = "SIGN";
    arrayOfString[1760] = "SILK";
    arrayOfString[1761] = "SILL";
    arrayOfString[1762] = "SILO";
    arrayOfString[1763] = "SILT";
    arrayOfString[1764] = "SINE";
    arrayOfString[1765] = "SING";
    arrayOfString[1766] = "SINK";
    arrayOfString[1767] = "SIRE";
    arrayOfString[1768] = "SITE";
    arrayOfString[1769] = "SITS";
    arrayOfString[1770] = "SITU";
    arrayOfString[1771] = "SKAT";
    arrayOfString[1772] = "SKEW";
    arrayOfString[1773] = "SKID";
    arrayOfString[1774] = "SKIM";
    arrayOfString[1775] = "SKIN";
    arrayOfString[1776] = "SKIT";
    arrayOfString[1777] = "SLAB";
    arrayOfString[1778] = "SLAM";
    arrayOfString[1779] = "SLAT";
    arrayOfString[1780] = "SLAY";
    arrayOfString[1781] = "SLED";
    arrayOfString[1782] = "SLEW";
    arrayOfString[1783] = "SLID";
    arrayOfString[1784] = "SLIM";
    arrayOfString[1785] = "SLIT";
    arrayOfString[1786] = "SLOB";
    arrayOfString[1787] = "SLOG";
    arrayOfString[1788] = "SLOT";
    arrayOfString[1789] = "SLOW";
    arrayOfString[1790] = "SLUG";
    arrayOfString[1791] = "SLUM";
    arrayOfString[1792] = "SLUR";
    arrayOfString[1793] = "SMOG";
    arrayOfString[1794] = "SMUG";
    arrayOfString[1795] = "SNAG";
    arrayOfString[1796] = "SNOB";
    arrayOfString[1797] = "SNOW";
    arrayOfString[1798] = "SNUB";
    arrayOfString[1799] = "SNUG";
    arrayOfString[1800] = "SOAK";
    arrayOfString[1801] = "SOAR";
    arrayOfString[1802] = "SOCK";
    arrayOfString[1803] = "SODA";
    arrayOfString[1804] = "SOFA";
    arrayOfString[1805] = "SOFT";
    arrayOfString[1806] = "SOIL";
    arrayOfString[1807] = "SOLD";
    arrayOfString[1808] = "SOME";
    arrayOfString[1809] = "SONG";
    arrayOfString[1810] = "SOON";
    arrayOfString[1811] = "SOOT";
    arrayOfString[1812] = "SORE";
    arrayOfString[1813] = "SORT";
    arrayOfString[1814] = "SOUL";
    arrayOfString[1815] = "SOUR";
    arrayOfString[1816] = "SOWN";
    arrayOfString[1817] = "STAB";
    arrayOfString[1818] = "STAG";
    arrayOfString[1819] = "STAN";
    arrayOfString[1820] = "STAR";
    arrayOfString[1821] = "STAY";
    arrayOfString[1822] = "STEM";
    arrayOfString[1823] = "STEW";
    arrayOfString[1824] = "STIR";
    arrayOfString[1825] = "STOW";
    arrayOfString[1826] = "STUB";
    arrayOfString[1827] = "STUN";
    arrayOfString[1828] = "SUCH";
    arrayOfString[1829] = "SUDS";
    arrayOfString[1830] = "SUIT";
    arrayOfString[1831] = "SULK";
    arrayOfString[1832] = "SUMS";
    arrayOfString[1833] = "SUNG";
    arrayOfString[1834] = "SUNK";
    arrayOfString[1835] = "SURE";
    arrayOfString[1836] = "SURF";
    arrayOfString[1837] = "SWAB";
    arrayOfString[1838] = "SWAG";
    arrayOfString[1839] = "SWAM";
    arrayOfString[1840] = "SWAN";
    arrayOfString[1841] = "SWAT";
    arrayOfString[1842] = "SWAY";
    arrayOfString[1843] = "SWIM";
    arrayOfString[1844] = "SWUM";
    arrayOfString[1845] = "TACK";
    arrayOfString[1846] = "TACT";
    arrayOfString[1847] = "TAIL";
    arrayOfString[1848] = "TAKE";
    arrayOfString[1849] = "TALE";
    arrayOfString[1850] = "TALK";
    arrayOfString[1851] = "TALL";
    arrayOfString[1852] = "TANK";
    arrayOfString[1853] = "TASK";
    arrayOfString[1854] = "TATE";
    arrayOfString[1855] = "TAUT";
    arrayOfString[1856] = "TEAL";
    arrayOfString[1857] = "TEAM";
    arrayOfString[1858] = "TEAR";
    arrayOfString[1859] = "TECH";
    arrayOfString[1860] = "TEEM";
    arrayOfString[1861] = "TEEN";
    arrayOfString[1862] = "TEET";
    arrayOfString[1863] = "TELL";
    arrayOfString[1864] = "TEND";
    arrayOfString[1865] = "TENT";
    arrayOfString[1866] = "TERM";
    arrayOfString[1867] = "TERN";
    arrayOfString[1868] = "TESS";
    arrayOfString[1869] = "TEST";
    arrayOfString[1870] = "THAN";
    arrayOfString[1871] = "THAT";
    arrayOfString[1872] = "THEE";
    arrayOfString[1873] = "THEM";
    arrayOfString[1874] = "THEN";
    arrayOfString[1875] = "THEY";
    arrayOfString[1876] = "THIN";
    arrayOfString[1877] = "THIS";
    arrayOfString[1878] = "THUD";
    arrayOfString[1879] = "THUG";
    arrayOfString[1880] = "TICK";
    arrayOfString[1881] = "TIDE";
    arrayOfString[1882] = "TIDY";
    arrayOfString[1883] = "TIED";
    arrayOfString[1884] = "TIER";
    arrayOfString[1885] = "TILE";
    arrayOfString[1886] = "TILL";
    arrayOfString[1887] = "TILT";
    arrayOfString[1888] = "TIME";
    arrayOfString[1889] = "TINA";
    arrayOfString[1890] = "TINE";
    arrayOfString[1891] = "TINT";
    arrayOfString[1892] = "TINY";
    arrayOfString[1893] = "TIRE";
    arrayOfString[1894] = "TOAD";
    arrayOfString[1895] = "TOGO";
    arrayOfString[1896] = "TOIL";
    arrayOfString[1897] = "TOLD";
    arrayOfString[1898] = "TOLL";
    arrayOfString[1899] = "TONE";
    arrayOfString[1900] = "TONG";
    arrayOfString[1901] = "TONY";
    arrayOfString[1902] = "TOOK";
    arrayOfString[1903] = "TOOL";
    arrayOfString[1904] = "TOOT";
    arrayOfString[1905] = "TORE";
    arrayOfString[1906] = "TORN";
    arrayOfString[1907] = "TOTE";
    arrayOfString[1908] = "TOUR";
    arrayOfString[1909] = "TOUT";
    arrayOfString[1910] = "TOWN";
    arrayOfString[1911] = "TRAG";
    arrayOfString[1912] = "TRAM";
    arrayOfString[1913] = "TRAY";
    arrayOfString[1914] = "TREE";
    arrayOfString[1915] = "TREK";
    arrayOfString[1916] = "TRIG";
    arrayOfString[1917] = "TRIM";
    arrayOfString[1918] = "TRIO";
    arrayOfString[1919] = "TROD";
    arrayOfString[1920] = "TROT";
    arrayOfString[1921] = "TROY";
    arrayOfString[1922] = "TRUE";
    arrayOfString[1923] = "TUBA";
    arrayOfString[1924] = "TUBE";
    arrayOfString[1925] = "TUCK";
    arrayOfString[1926] = "TUFT";
    arrayOfString[1927] = "TUNA";
    arrayOfString[1928] = "TUNE";
    arrayOfString[1929] = "TUNG";
    arrayOfString[1930] = "TURF";
    arrayOfString[1931] = "TURN";
    arrayOfString[1932] = "TUSK";
    arrayOfString[1933] = "TWIG";
    arrayOfString[1934] = "TWIN";
    arrayOfString[1935] = "TWIT";
    arrayOfString[1936] = "ULAN";
    arrayOfString[1937] = "UNIT";
    arrayOfString[1938] = "URGE";
    arrayOfString[1939] = "USED";
    arrayOfString[1940] = "USER";
    arrayOfString[1941] = "USES";
    arrayOfString[1942] = "UTAH";
    arrayOfString[1943] = "VAIL";
    arrayOfString[1944] = "VAIN";
    arrayOfString[1945] = "VALE";
    arrayOfString[1946] = "VARY";
    arrayOfString[1947] = "VASE";
    arrayOfString[1948] = "VAST";
    arrayOfString[1949] = "VEAL";
    arrayOfString[1950] = "VEDA";
    arrayOfString[1951] = "VEIL";
    arrayOfString[1952] = "VEIN";
    arrayOfString[1953] = "VEND";
    arrayOfString[1954] = "VENT";
    arrayOfString[1955] = "VERB";
    arrayOfString[1956] = "VERY";
    arrayOfString[1957] = "VETO";
    arrayOfString[1958] = "VICE";
    arrayOfString[1959] = "VIEW";
    arrayOfString[1960] = "VINE";
    arrayOfString[1961] = "VISE";
    arrayOfString[1962] = "VOID";
    arrayOfString[1963] = "VOLT";
    arrayOfString[1964] = "VOTE";
    arrayOfString[1965] = "WACK";
    arrayOfString[1966] = "WADE";
    arrayOfString[1967] = "WAGE";
    arrayOfString[1968] = "WAIL";
    arrayOfString[1969] = "WAIT";
    arrayOfString[1970] = "WAKE";
    arrayOfString[1971] = "WALE";
    arrayOfString[1972] = "WALK";
    arrayOfString[1973] = "WALL";
    arrayOfString[1974] = "WALT";
    arrayOfString[1975] = "WAND";
    arrayOfString[1976] = "WANE";
    arrayOfString[1977] = "WANG";
    arrayOfString[1978] = "WANT";
    arrayOfString[1979] = "WARD";
    arrayOfString[1980] = "WARM";
    arrayOfString[1981] = "WARN";
    arrayOfString[1982] = "WART";
    arrayOfString[1983] = "WASH";
    arrayOfString[1984] = "WAST";
    arrayOfString[1985] = "WATS";
    arrayOfString[1986] = "WATT";
    arrayOfString[1987] = "WAVE";
    arrayOfString[1988] = "WAVY";
    arrayOfString[1989] = "WAYS";
    arrayOfString[1990] = "WEAK";
    arrayOfString[1991] = "WEAL";
    arrayOfString[1992] = "WEAN";
    arrayOfString[1993] = "WEAR";
    arrayOfString[1994] = "WEED";
    arrayOfString[1995] = "WEEK";
    arrayOfString[1996] = "WEIR";
    arrayOfString[1997] = "WELD";
    arrayOfString[1998] = "WELL";
    arrayOfString[1999] = "WELT";
    arrayOfString[2000] = "WENT";
    arrayOfString[2001] = "WERE";
    arrayOfString[2002] = "WERT";
    arrayOfString[2003] = "WEST";
    arrayOfString[2004] = "WHAM";
    arrayOfString[2005] = "WHAT";
    arrayOfString[2006] = "WHEE";
    arrayOfString[2007] = "WHEN";
    arrayOfString[2008] = "WHET";
    arrayOfString[2009] = "WHOA";
    arrayOfString[2010] = "WHOM";
    arrayOfString[2011] = "WICK";
    arrayOfString[2012] = "WIFE";
    arrayOfString[2013] = "WILD";
    arrayOfString[2014] = "WILL";
    arrayOfString[2015] = "WIND";
    arrayOfString[2016] = "WINE";
    arrayOfString[2017] = "WING";
    arrayOfString[2018] = "WINK";
    arrayOfString[2019] = "WINO";
    arrayOfString[2020] = "WIRE";
    arrayOfString[2021] = "WISE";
    arrayOfString[2022] = "WISH";
    arrayOfString[2023] = "WITH";
    arrayOfString[2024] = "WOLF";
    arrayOfString[2025] = "WONT";
    arrayOfString[2026] = "WOOD";
    arrayOfString[2027] = "WOOL";
    arrayOfString[2028] = "WORD";
    arrayOfString[2029] = "WORE";
    arrayOfString[2030] = "WORK";
    arrayOfString[2031] = "WORM";
    arrayOfString[2032] = "WORN";
    arrayOfString[2033] = "WOVE";
    arrayOfString[2034] = "WRIT";
    arrayOfString[2035] = "WYNN";
    arrayOfString[2036] = "YALE";
    arrayOfString[2037] = "YANG";
    arrayOfString[2038] = "YANK";
    arrayOfString[2039] = "YARD";
    arrayOfString[2040] = "YARN";
    arrayOfString[2041] = "YAWL";
    arrayOfString[2042] = "YAWN";
    arrayOfString[2043] = "YEAH";
    arrayOfString[2044] = "YEAR";
    arrayOfString[2045] = "YELL";
    arrayOfString[2046] = "YOGA";
    arrayOfString[2047] = "YOKE";
    Random random = new Random();
    int i = random.nextInt(256);
    int j = random.nextInt(256);
    return arrayOfString[i] + " " + arrayOfString[j];
  }
  
  private void processExtrasAndData(Intent paramIntent, boolean paramBoolean) {
    Bundle bundle = paramIntent.getExtras();
    if (bundle != null) {
      Log.d(LOG_TAG, "extras: " + bundle);
      Iterator<String> iterator = bundle.keySet().iterator();
      while (iterator.hasNext())
        Log.d(LOG_TAG, "Extra Key: " + (String)iterator.next()); 
    } 
    String str = paramIntent.getDataString();
    if (str != null && str.startsWith("aicompanion")) {
      this.isDirect = true;
      this.assetsLoaded = true;
    } 
    if (bundle != null && bundle.getBoolean("rundirect")) {
      Log.d(LOG_TAG, "processExtrasAndData rundirect is true and restart is " + paramBoolean);
      this.isDirect = true;
      this.assetsLoaded = true;
      if (paramBoolean) {
        clear();
        if (this.httpdServer != null) {
          this.httpdServer.resetSeq();
          return;
        } 
      } else {
        return;
      } 
    } else {
      return;
    } 
    startHTTPD(true);
    AppInvHTTPD appInvHTTPD = this.httpdServer;
    AppInvHTTPD.setHmacKey("emulator");
  }
  
  public static void returnRetvals(String paramString) {
    ReplForm replForm = (ReplForm)activeForm;
    Log.d(LOG_TAG, "returnRetvals: " + paramString);
    replForm.sendToCompanion(paramString);
  }
  
  private void startChromebook(String paramString) {
    String str1 = paramString.substring(paramString.indexOf("//comp/") + 7);
    PhoneStatus phoneStatus = new PhoneStatus(this);
    phoneStatus.WebRTC(true);
    str1 = phoneStatus.setHmacSeedReturnCode(str1, "rendezvous.appinventor.mit.edu");
    String str2 = PhoneStatus.GetWifiIpAddress();
    int i = phoneStatus.SdkLevel();
    String str3 = phoneStatus.GetVersionName();
    String str4 = phoneStatus.InstallationId();
    Log.d(LOG_TAG, "InstallationId = " + str4);
    Web web = new Web(this);
    web.Url("http://rendezvous.appinventor.mit.edu/rendezvous/");
    web.PostText("ipaddr=" + str2 + "&port=9987&webrtc=true&version=" + str3 + "&api=" + i + "&aid=" + str4 + "&installer=" + phoneStatus.GetInstaller() + "&r2=true&key=" + str1);
    phoneStatus.startWebRTC("rendezvous.appinventor.mit.edu", "OK");
  }
  
  void HandleReturnValues() {
    Log.d(LOG_TAG, "HandleReturnValues() Called, replResult = " + this.replResult);
    if (this.replResult != null) {
      OtherScreenClosed(this.replResultFormName, this.replResult);
      Log.d(LOG_TAG, "Called OtherScreenClosed");
      this.replResult = null;
    } 
  }
  
  @SimpleProperty(userVisible = false)
  public void Theme(String paramString) {
    this.currentTheme = paramString;
    super.Theme(paramString);
    updateTitle();
  }
  
  public void addLogcatButton(Menu paramMenu) {
    if (!ReplApplication.isAcraActive())
      return; 
    paramMenu.add(0, 0, 4, "Send Error Report").setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem param1MenuItem) {
            String str = ReplForm.this.genReportId();
            ReplApplication.reportError(null, str);
            Notifier.oneButtonAlert(Form.activeForm, "Your Report Id is: " + str + "<br />Use this ID when reporting this error.", "Error Report Id", "OK");
            return true;
          }
        }).setIcon(17301642);
  }
  
  public void addSettingsButton(Menu paramMenu) {
    paramMenu.add(0, 0, 3, "Settings").setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem param1MenuItem) {
            PhoneStatus.doSettings();
            return true;
          }
        }).setIcon(17301651);
  }
  
  protected void closeApplicationFromBlocks() {
    runOnUiThread(new Runnable() {
          public void run() {
            Toast.makeText((Context)ReplForm.this, "Closing forms is not currently supported during development.", 1).show();
          }
        });
  }
  
  protected void closeForm(Intent paramIntent) {
    RetValManager.popScreen("Not Yet");
  }
  
  public void evalScheme(String paramString) {
    this.schemeInterface.eval(paramString);
  }
  
  public String getAssetPath(String paramString) {
    return "file://" + this.replAssetDir + paramString;
  }
  
  public String getAssetPathForExtension(Component paramComponent, String paramString) throws FileNotFoundException {
    SimpleObject simpleObject1 = paramComponent.getClass().<SimpleObject>getAnnotation(SimpleObject.class);
    if (simpleObject1 != null && !simpleObject1.external())
      return "file:///android_asset/" + paramString; 
    String str = paramComponent.getClass().getName();
    SimpleObject simpleObject2 = null;
    while (true) {
      String str1;
      simpleObject1 = simpleObject2;
      if (str.contains(".")) {
        File file = new File(this.replCompDir + str + "/assets");
        if (file.exists() && file.isDirectory()) {
          str1 = file.getAbsolutePath();
        } else {
          str = str.substring(0, str.lastIndexOf('.'));
          continue;
        } 
      } 
      if (str1 != null) {
        File file = new File(str1, paramString);
        Log.d(LOG_TAG, "result = " + file.getAbsolutePath());
        if (file.exists())
          return "file://" + file.getAbsolutePath(); 
      } 
      break;
    } 
    throw new FileNotFoundException();
  }
  
  public boolean isAssetsLoaded() {
    return this.assetsLoaded;
  }
  
  public boolean isDirect() {
    return this.isDirect;
  }
  
  protected boolean isRepl() {
    return true;
  }
  
  public void loadComponents(List<String> paramList) {
    HashSet<String> hashSet = new HashSet<String>(paramList);
    File file1 = activeForm.$context().getDir("componentDexs", 0);
    File file2 = new File(this.replCompDir);
    if (!checkComponentDir()) {
      Log.d(LOG_TAG, "Unable to create components directory");
      dispatchErrorOccurredEventDialog(this, "loadComponents", 3300, new Object[] { Integer.valueOf(1), "App Inventor", "Unable to create component directory." });
      return;
    } 
    ClassLoader classLoader = ReplForm.class.getClassLoader();
    StringBuilder stringBuilder = new StringBuilder();
    this.loadedExternalDexs.clear();
    for (File file : file2.listFiles()) {
      if (file.isDirectory() && hashSet.contains(file.getName())) {
        File file3 = new File(file.getPath() + File.separator + "classes.jar");
        file = new File(file.getPath() + File.separator + file.getName() + ".jar");
        file3.renameTo(file);
        if (file.exists() && !this.loadedExternalDexs.contains(file.getName())) {
          Log.d(LOG_TAG, "Loading component dex " + file.getAbsolutePath());
          this.loadedExternalDexs.add(file.getName());
          stringBuilder.append(File.pathSeparatorChar);
          stringBuilder.append(file.getAbsolutePath());
        } 
      } 
    } 
    DexClassLoader dexClassLoader = new DexClassLoader(stringBuilder.substring(1), file1.getAbsolutePath(), null, classLoader);
    Thread.currentThread().setContextClassLoader((ClassLoader)dexClassLoader);
    Log.d(LOG_TAG, Thread.currentThread().toString());
    Log.d(LOG_TAG, Looper.getMainLooper().getThread().toString());
    Looper.getMainLooper().getThread().setContextClassLoader((ClassLoader)dexClassLoader);
  }
  
  public void onCreate(Bundle paramBundle) {
    Log.d(LOG_TAG, "onCreate");
    this.replAssetDir = QUtil.getReplAssetPath((Context)this);
    this.replCompDir = this.replAssetDir + "external_comps/";
    super.onCreate(paramBundle);
    this.loadedExternalDexs = new ArrayList<String>();
    processExtrasAndData(getIntent(), false);
    this.themeHelper.setActionBarAnimation(false);
  }
  
  void onCreateFinish() {
    super.onCreateFinish();
    Log.d(LOG_TAG, "onCreateFinish() Called in Repl");
    checkAssetDir();
    checkComponentDir();
    if (!isEmulator() && AppInventorFeatures.doCompanionSplashScreen()) {
      Intent intent1 = new Intent("android.intent.action.MAIN");
      intent1.setClassName((Context)activeForm.$context(), SPLASH_ACTIVITY_CLASS);
      activeForm.$context().startActivity(intent1);
    } 
    Intent intent = getIntent();
    Log.d(LOG_TAG, "Intent = " + intent);
    final String data = intent.getDataString();
    if (str != null) {
      Log.d(LOG_TAG, "Got data = " + str);
    } else {
      Log.d(LOG_TAG, "Did not receive any data");
    } 
    if (str != null && str.startsWith("aicompanion"))
      registerForOnInitialize(new OnInitializeListener() {
            public void onInitialize() {
              ReplForm.this.startChromebook(data);
            }
          }); 
  }
  
  public boolean onCreateOptionsMenu(Menu paramMenu) {
    super.onCreateOptionsMenu(paramMenu);
    addSettingsButton(paramMenu);
    addLogcatButton(paramMenu);
    return true;
  }
  
  protected void onDestroy() {
    super.onDestroy();
    if (this.httpdServer != null) {
      this.httpdServer.stop();
      this.httpdServer = null;
    } 
    finish();
    System.exit(0);
  }
  
  protected void onNewIntent(Intent paramIntent) {
    super.onNewIntent(paramIntent);
    Log.d(LOG_TAG, "onNewIntent Called");
    processExtrasAndData(paramIntent, true);
    String str = paramIntent.getDataString();
    if (str != null && str.startsWith("aicompanion"))
      startChromebook(str); 
  }
  
  protected void onResume() {
    super.onResume();
  }
  
  protected void onStop() {
    super.onStop();
  }
  
  public void sendToCompanion(String paramString) {
    if (this.webRTCNativeMgr == null) {
      Log.i(LOG_TAG, "No WebRTCNativeMgr!");
      return;
    } 
    this.webRTCNativeMgr.send(paramString);
  }
  
  public void setAssetsLoaded() {
    this.assetsLoaded = true;
  }
  
  public void setFormName(String paramString) {
    this.formName = paramString;
    Log.d(LOG_TAG, "formName is now " + paramString);
  }
  
  public void setIsUSBrepl() {
    this.IsUSBRepl = true;
  }
  
  protected void setResult(Object paramObject) {
    Log.d(LOG_TAG, "setResult: " + paramObject);
    this.replResult = paramObject;
    this.replResultFormName = this.formName;
  }
  
  public void setWebRTCMgr(WebRTCNativeMgr paramWebRTCNativeMgr) {
    this.webRTCNativeMgr = paramWebRTCNativeMgr;
  }
  
  public void startHTTPD(boolean paramBoolean) {
    try {
      if (this.httpdServer == null) {
        checkAssetDir();
        this.httpdServer = new AppInvHTTPD(8001, new File(this.replAssetDir), paramBoolean, this);
        Log.i(LOG_TAG, "started AppInvHTTPD");
      } 
      return;
    } catch (IOException iOException) {
      Log.e(LOG_TAG, "Setting up NanoHTTPD: " + iOException.toString());
      return;
    } 
  }
  
  protected void startNewForm(String paramString, Object paramObject) {
    if (paramObject != null)
      this.startupValue = jsonEncodeForForm(paramObject, "open another screen with start value"); 
    RetValManager.pushScreen(paramString, paramObject);
  }
  
  protected void updateTitle() {
    this.themeHelper.setTitle(this.title, "AppTheme.Light".equals(this.currentTheme));
  }
  
  public class SchemeInterface {
    Language scheme = Scheme.getInstance("scheme");
    
    public SchemeInterface() {
      ModuleExp.mustNeverCompile();
    }
    
    private void adoptMainThreadClassLoader() {
      ClassLoader classLoader = Looper.getMainLooper().getThread().getContextClassLoader();
      Thread thread = Thread.currentThread();
      if (thread.getContextClassLoader() != classLoader)
        thread.setContextClassLoader(classLoader); 
    }
    
    public void eval(final String sexp) {
      ReplForm.this.runOnUiThread(new Runnable() {
            public void run() {
              try {
                ReplForm.SchemeInterface.this.adoptMainThreadClassLoader();
                if (sexp.equals("#DONE#")) {
                  ReplForm.this.finish();
                  return;
                } 
                ReplForm.SchemeInterface.this.scheme.eval(sexp);
                return;
              } catch (Throwable throwable) {
                Log.e(ReplForm.LOG_TAG, "Exception in scheme processing", throwable);
                return;
              } 
            }
          });
    }
  }
  
  class null implements Runnable {
    public void run() {
      try {
        this.this$1.adoptMainThreadClassLoader();
        if (sexp.equals("#DONE#")) {
          ReplForm.this.finish();
          return;
        } 
        this.this$1.scheme.eval(sexp);
        return;
      } catch (Throwable throwable) {
        Log.e(ReplForm.LOG_TAG, "Exception in scheme processing", throwable);
        return;
      } 
    }
  }
}


/* Location:              /home/geo/hackathon/GROW/apk/dex2jar-2.0/classes-dex2jar.jar!/com/google/appinventor/components/runtime/ReplForm.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */